### ISSUE TITLE
Level calculation build 295

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Level#101]
**Description**
Build 295 introduces weird level calculation causing all existing islands to lose much levels. Placing this build on a production server makes every island to lose up to 1000 levels. This makes players unhappy. Reverting to build 294 (or lower) resolves it.

**Steps to reproduce the behavior:**
1. Start default test server with empty world
2. Start default island (the one with the moomoo cow)
3. Calculate `is level` (I used my own custom level values)
4. Check level file
```
{
  "uniqueId": "my-uuid",
  "levels": {
    "bskyblock_world": -2
  },
  "initialLevel": {
    "bskyblock_world": 186
  }
}
```
5. Placing 1000 blocks with value 4 = 4000, = 40 is levels
6. Calculate `is level`
7. Check level file
```
{
  "uniqueId": "my-uuid",
  "levels": {
    "bskyblock_world": 38
  },
  "initialLevel": {
    "bskyblock_world": 186
  }
}
```
8. Stop server, replace add on Level build 294 with build 295, start server again
9. Login and calculate `is level`
10. Check level file that has changed
```
{
  "uniqueId": "my-uuid",
  "levels": {
    "bskyblock_world": -145
  },
  "initialLevel": {
    "bskyblock_world": 186
  }
}
```
Placing another 1000 blocks makes the level increase with another 40 levels, however it still counts from the new negative island level.

**Expected behavior**
Level calculation like it used to do before

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - OS:  Linux
 - Java Version:  Openjdk 1.8.0_212
 - BentoBox version: 1.9.0 build 1486
 - Addons installed?
```
Running PAPER 1.14.4.
BentoBox version: 1.9.0-SNAPSHOT-b1486
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.1-SNAPSHOT-b149 (ENABLED)
BSkyBlock 1.9.0-SNAPSHOT-b525 (ENABLED)
Challenges 0.9.0-SNAPSHOT-#393 (ENABLED)
Level 1.8.1-SNAPSHOT-b295 (ENABLED)
Limits 1.9.0-SNAPSHOT-b179 (ENABLED)
MagicCobblestoneGenerator 1.7.1-SNAPSHOT-#83 (ENABLED)
Warps 1.8.2-SNAPSHOT-b201 (ENABLED)
```
 - Other plugins? `BentoBox, ChestShop, dynmap*, LuckPerms, mcMMO, PlaceholderAPI*, PlugMan, Vault, WorldBorder, WorldEdit, WorldGuard`

**Additional context**
Starting the same island from scratch again with build 295 gets completely different level initial information:
```
{
  "uniqueId": "my-uuid",
  "levels": {
    "bskyblock_world": 0
  },
  "initialLevel": {
    "bskyblock_world": 1
  }
}

**Comment by tastybento** [comment]
In the console you can get a full report on the level. Can you do `bsb level (your name)` in console with the old build and new build and then paste them so I can see them?

**Comment by tastybento** [comment]
Also, please try the latest build from the CI.

**Comment by x1p** [comment]
https://hastebin.com/poxejafome.md
Latest 306 build: https://hastebin.com/vodeleripi.md

**Comment by tastybento** [comment]
Looks like Nether and End island calculations are just being missed. I'll fix.

**Comment by tastybento** [comment]
It should be fixed now. Please try it.
