### ISSUE TITLE
Placeholder: Members of the islands in the top 10

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Level#107]
**Description**

Requested by @Deathinflames in https://github.com/BentoBoxWorld/BentoBox/issues/882.

Original request:
> which [the placeholder] would return the number 1 top island team members like this: name1, name2, name3, etc.

I suggest instead that we extend it to be able to work with all islands in the top.

**Placeholder**: `Level_[gamemode]_top_members_#RANK#_#id#`

**Comment by tastybento** [comment]
What are the definitions of RANK and id in this case?

**Comment by Poslovitch** [comment]
Rank is the rank of the island in the top ten, id is the "number" of the island member.

**Comment by tastybento** [comment]
Hmm, there is no ordering of team members, and in theory, a team could be huge, so hard coding and registering team member names as name1, name2, name3, etc. seems a bit weird. Whoever would be using these placeholders will have no idea what number to go up to. How about returning a string of comma-separated team member names, like "tastybento, Poslovitch, BONNe" etc?

**Comment by Poslovitch** [comment]
Well some might want it comma separated, others might want that as a list...

**Comment by tastybento** [comment]
Yes, so how to do that? Maybe have two different placeholders?

**Comment by Poslovitch** [comment]
Let's just go with comma separated values for now.
