### ISSUE TITLE
Last dev build level#329 problemly.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Level#109]
#### Describe the bug
![image](https://user-images.githubusercontent.com/47111280/71198025-f98cf680-22a3-11ea-8ba5-043e6b227bb7.png)

Not calculate islands levels. Same error when type /is level

**Comment by tastybento** [comment]
Thanks. I reverted that commit. 09583aa3a719ad87a4e2a8930a035d2d36e41408
