### ISSUE TITLE
deprecated placeholder.,what should i do

### ISSUE THREAD

**Issue by vip878269086** [BentoBoxWorld/Level#113]
>.... [02:31:47 WARN]: [BentoBox] [Level] You are using a deprecated placeholder.
>.... [02:31:47 INFO]: [BentoBox] [Level] Please replace any occurrence of 'Level_bskyblock-island-level'
>.... [02:31:47 INFO]: [BentoBox] [Level] by 'Level_bskyblock_island_level'
>.... [02:31:47 WARN]: [BentoBox] [Level] You are using a deprecated placeholder.
>.... [02:31:47 INFO]: [BentoBox] [Level] Please replace any occurrence of 'Level_acidisland-island-level'
>.... [02:31:47 INFO]: [BentoBox] [Level] by 'Level_acidisland_island_level'
>.... [02:31:47 WARN]: [BentoBox] [Level] You are using a deprecated placeholder

>.... [02:42:40 INFO]: 正在运行 PAPER 1.14.4.
>.... [02:42:40 INFO]: Bentobox 版本：1.10.0-SNAPSHOT-b1539
>.... [02:42:40 INFO]: 数据库：JSON
>.... [02:42:40 INFO]: 已加载游戏世界：
>.... [02:42:40 INFO]: acidisland_world (AcidIsland): &主世界, 地狱, 末界
>.... [02:42:40 INFO]: bskyblock_world (BSkyBlock): &主世界, 地狱, 末界
>.... [02:42:40 INFO]: caveblock-world (CaveBlock): &主世界, 地狱, 末界
>.... [02:42:40 INFO]: 已加载扩展：
>.... [02:42:40 INFO]: AcidIsland 1.10.0-SNAPSHOT-b559 (ENABLED)
>.... [02:42:40 INFO]: Biomes 1.6.0.2-SNAPSHOT-b142 (ENABLED)
>.... [02:42:40 INFO]: Border 1.0.2 (ENABLED)
>.... [02:42:40 INFO]: BSkyBlock 1.10.0-SNAPSHOT-b563 (ENABLED)
'>.... [02:42:40 INFO]: CaveBlock 1.9.0-SNAPSHOT-b246 (ENABLED)
>.... [02:42:40 INFO]: Challenges 0.9.0-SNAPSHOT-#395 (ENABLED)
>.... [02:42:40 INFO]: ControlPanel 1.7.0 (ENABLED)
>.... [02:42:40 INFO]: DimensionalTrees 1.6.0-SNAPSHOT-b78 (ENABLED)
>.... [02:42:40 INFO]: Greenhouses 1.0.0 (ENABLED)
>.... [02:42:40 INFO]: Level 1.9.1-SNAPSHOT-b330 (ENABLED)
>.... [02:42:40 INFO]: Likes 1.7.0-SNAPSHOT-#14 (ENABLED)
>.... [02:42:40 INFO]: Limits 1.9.0 (ENABLED)
>.... [02:42:40 INFO]: MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b92 (ENABLED)
>.... [02:42:40 INFO]: VoidPortals 1.5.0.1-SNAPSHOT-b73 (ENABLED)
>.... [02:42:40 INFO]: Warps 1.9.2-SNAPSHOT-b217 (ENABLED)

**Comment by Poslovitch** [comment]
It is written in plain text.

>  [Level] Please replace any occurrence of 'Level_acidisland-island-level' by 'Level_acidisland_island_level'

However, since I received some complaints about these messages spamming the console, I will remove these warnings. Yet make sure you're no longer using the deprecated placeholders, since they will stop working at some point.

**Comment by vip878269086** [comment]
Where can i change it

**Comment by tastybento** [comment]
Do you have a plugin that is using BentoBox placeholders to show a scoreboard?

**Comment by Poslovitch** [comment]
As a quick note, I got rid of the messages. If you use a snapshot for Level, you should no longer see them in the console, but you will have to make sure you're no longer using them, as they may stop working in the future.

**Comment by vip878269086** [comment]
I found it，thinks
