### ISSUE TITLE
Proper event handling

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/Level#118]
#### Describe the bug

IslandLevelCalculatedEvent class as one of the variables (result) is using Level addon class, which is not available to outside BentoBoxWorld, due classLoader. 
So people, who want to use this event to get calculated value, cannot access to it in their plugins.
It means, either it is necessary to somehow allow access to addon classes or even should return primitive values or mapped values, instead of internal class.

### Additional context (Optional)

It comes up a lot in the discord API channel.

**Comment by tastybento** [comment]
Does this commit do what is required?

**Comment by BONNe** [comment]
Yes, thanks :)
