### ISSUE TITLE
Change Island's level using API

### ISSUE THREAD

**Issue by iBuseWinner** [BentoBoxWorld/Level#125]
Hello. Please add the ability to change island levels through events.

IslandPreLevelEvent:
event.getIsland().setLevel(...);

IslandLevelCalculatedEvent:
Results res = new Results();
res.setLevel(...);

event.setResults(res);

OR
event.getIsland().setLevel(...);

**Comment by tastybento** [comment]
This is supported (or should be). That’s why there are two events. I’m on my phone right now but I’ll look at documenting this.

**Comment by tastybento** [comment]
Okay, you need to listen for the `IslandLevelCalculatedEvent` and then use `setLevel` to set the level to what you want. If you are a plugin then you can set it using the `setLevel(long)`. If you are an addon, then you can create a new Results class and fill it how you like.

**Comment by tastybento** [comment]
So, please try the latest build and let me know if it works for you.

**Comment by marko-pilipovicc** [comment]
My plugin can't seem to recognise the classpath for the levels addon

**Comment by BONNe** [comment]
Plugins cannot directly access any classes inside an addon because of Java security rules on class loaders.
