### ISSUE TITLE
[Suggestion]optimise /is level and /is top

### ISSUE THREAD

**Issue by Alice-space** [BentoBoxWorld/Level#128]
### Description
please optimise /is top and /is level query. Each time I use one of these commands, the server doesn`t response for a while.
Why not try a better way such as recording when a player set or destory a block,instead of calculating after command issued.
 (sorry English is not my native language.)

**Comment by tastybento** [comment]
You can adjust the performance settings in config.yml:
```
# Performance settings
# Level is very processor-intensive, so these settings may need to be tweaked to optimize for your server
# Delay between each task that loads chunks for calculating levels
# Increasing this will slow down level calculations but reduce average load
task-delay: 1

# Number of chunks that will be processed per task
chunks: 10
```

We are as optimized as possible. The way you suggest is used in the Limits addon, but can get out of sync quite easily and eventually requires a full recount.
