### ISSUE TITLE
issue with /top

### ISSUE THREAD

**Issue by ieryana** [BentoBoxWorld/Level#131]
### Description

After a restart on the server /[game] top has reset - doesn#t appear to be secure in palce holder.
also /sg top isn't working at all.

#### Steps to reproduce the behavior
Get a /[game] top - restart server and do it again, will have wiped.
Using mysql.
Try and do /sg top.

#### Expected behavior
The Top scoreboards remain even after a restart

##### BentoBox Version (Mandatory)
1.11

**Comment by tastybento** [comment]
Is this a new install or was it working fine and then suddenly stopped working?

Please do `bbox version` in the console and share the output. 

Also, as it is something to do with restarting, share your before reboot log and after reboot log. You can find zipped copies in the logs folder of the server. Just drag and drop them into this ticket to attach them.

**Comment by ieryana** [comment]
It has never worked on /sg since we installed.
And it's always happened with the reboot - I'll get the files to you when I get into my office x
