### ISSUE TITLE
Placeholder %Level_caveblock-island-level% always show 0

### ISSUE THREAD

**Issue by MorkaZ** [BentoBoxWorld/Level#134]
#### Describe the bug

Placeholder Level_caveblock-island-level completly does not work - it is always 0.

#### Steps to reproduce the behavior

Just use %Level_caveblock-island-level% placeholder in any plugin that supports PlaceholderAPI placeholders with "Caveblock" and "Levels" addons installed.

#### Expected behavior

Real level output in placeholder instead of 0.

#### Screenshots and videos (Optional)

![image](https://user-images.githubusercontent.com/4214815/76153755-ecc4b580-60d0-11ea-9850-4f39596d71fb.png)
![image](https://user-images.githubusercontent.com/4214815/76153756-f2220000-60d0-11ea-8ad9-8c6dfe87b1cd.png)
![image](https://user-images.githubusercontent.com/4214815/76153757-f5b58700-60d0-11ea-8a3f-642a5105f0f2.png)

### Environment
Latest paper-spigot 1.15.2
GAME-3 Dedicated server from OVH.com
Java 8
MariaDB
Debian 9

##### BentoBox Version (Mandatory)

```
1.11.1
```

#### Plugins (Optional)

```
[00:09:55 INFO]: Plugins (39): antiRedstoneClock, AuctionHouse, BentoBox, BossShopPro, ChatInjector*, ColoredSigns*, CommandButtons, CraftBook, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, HeadDatabase*, HolographicDisplays, ItemShops*, MorkazSk, MoxChatTitles, MoxCore, MoxPerms*, MoxPremiumShop, MoxTokensDatabase*, MoxTransmutators, Multiverse-Core*, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolSupport, SK-NBeeT, SkQuery, skRayFall*, Skript, SQLibrary*, TAB, TuSKe*, Vault, WorldBorder, WorldBorderAPI*, WorldEdit, WorldGuard

```

**Comment by MorkaZ** [comment]
I do not know what happened but after server restart it started working propetly.  
I was setting up my new, fresh made server. Maybe this happens when server is fresh and everything is on first run?

**Comment by MorkaZ** [comment]
I do not know what happened but after server restart it started working propetly.
I was setting up my new, fresh made server. Maybe this happens when server is fresh and everything is on first run?
This problem may be also random and if yes then I was unlucky in that moment. Very weird :/

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/Level/wiki/Placeholders#generic-placeholders

**Comment by MorkaZ** [comment]
Yeah, placeholder is correct. The problem is why it was showing 0 on any player when this player had other level. It was first start of this addon, problem disappeared after restart.

**Comment by tastybento** [comment]
Placeholders are complex. They need to be registered with the Placeholder API plugin and so can be broken with a reload. A fresh restart is strongly recommended. If you see issues even after that, then let us know.

**Comment by MorkaZ** [comment]
Now I am sure what caused this problem. I realised that I executed /bentobox reload to reload translated messages.
