### ISSUE TITLE
Add 1.15.x blocks to the list

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Level#135]
#### Is your feature request related to a problem?

The 1.15.x blocks are seemingly not part of the config.

#### Describe the solution you'd like us to implement.

Add the 1.15.x blocks to the config.

#### Describe alternatives you've considered.

None.

### Additional context

None.

**Comment by tastybento** [comment]
Yes, I agree. I have been playing on a 1.15.2 server and found a number of my hard-crafted blocks we worth zero!
