### ISSUE TITLE
Problem with the placeholder LEVEL

### ISSUE THREAD

**Issue by AFGAME** [BentoBoxWorld/Level#145]
Good morning, sir,

The placeholder level: %Level_bskyblock_visited_island_level% this suddenly stops working, it works fine and suddenly it doesn't work anymore, it displays the last /is level executing, sometimes it takes up to 3 server restarts for it to work again. I hope I have been clear in this writing.

Codially,
AFGAME

**Comment by tastybento** [comment]
Can you run `/bbox v` and then copy and paste the result to this ticket so I can check what versions of everything you are running?

**Comment by AFGAME** [comment]
http://prntscr.com/s2g82l

**Comment by tastybento** [comment]
Could you try the latest snapshot release 2.0.0? Also, make a backup before doing so. It should work find, but I don't want to cause you more problems if it does not.

**Comment by AFGAME** [comment]
It's possible to give me the link

**Comment by AFGAME** [comment]
![image](https://user-images.githubusercontent.com/50768722/79735042-f6f4e900-82f7-11ea-821c-e52a5873949b.png)
oh its not good 2.0.0 :c

**Comment by AFGAME** [comment]
oh no it's good, because i download 
![image](https://user-images.githubusercontent.com/50768722/79735304-5a7f1680-82f8-11ea-8563-a17e9a3e8095.png)
when I had to take 
![image](https://user-images.githubusercontent.com/50768722/79735326-679c0580-82f8-11ea-8502-6ba56506153d.png)

**Comment by AFGAME** [comment]
ah actually version 2.0.0 added a lot of level to the player I went from 159 to 37800

**Comment by tastybento** [comment]
Okay, that's a bug.
Can you do `/bsb level` on yourself in the console and then share it? Don't use a screenshot - you'll need to be in the console and copy and paste the text because there's a lot of it.

**Comment by AFGAME** [comment]
Uh I put the old version back because I have players and I don't want it to be a problem

**Comment by tastybento** [comment]
I found the bug - AIR had one point of value.

**Comment by AFGAME** [comment]
Okay, so what does that mean?

**Comment by tastybento** [comment]
In the blockvalues.yml file (which is new) it had AIR listed as 1 so that meant you got 1 point for every air block instead of 0 so the level was super high. I'll fix and do more testing and then it should be working. Sorry for the bother.

**Comment by AFGAME** [comment]
Ok no worries, well when you have a new version send it to me and I'll test it for you.

**Comment by tastybento** [comment]
Please test https://ci.codemc.io/job/BentoBoxWorld/job/Level/352/

**Comment by AFGAME** [comment]
It's all right, it's all right, if I have a problem as mentioned before I'll let you know!
