### ISSUE TITLE
Command /is value don't detect any block value in blockconfig.yml

### ISSUE THREAD

**Issue by Blatower21** [BentoBoxWorld/Level#148]
**Description:**
When you write /is value it said that the block you have in hand don't have value, no matter what block you are holding.

**Steps to reproduce the behavior:**
- Write /is value with an item in hand

**Expected behavior:**
Show correctly the value of the item in blockconfig.yml

**Image of /is value with a beacon in hand don't showing the value of the block for example**
![2020-04-21_14 26 00](https://user-images.githubusercontent.com/31895420/79894840-6ba15380-83dc-11ea-940c-7bfb0377d29b.png)

**Environment**
`[00:16:09] [Server thread/INFO]: Corriendo PAPER 1.15.2.`
`[00:16:09] [Server thread/INFO]: BentoBox version: 1.13.0-SNAPSHOT-b1734`
`[00:16:09] [Server thread/INFO]: Base de datos: MARIADB`
`[00:16:09] [Server thread/INFO]: Mundos de juego cargados:`
`[00:16:09] [Server thread/INFO]: bskyblock_world (BSkyBlock): Mundo, Nether, End`
`[00:16:09] [Server thread/INFO]: Addons cargados:`
`[00:16:09] [Server thread/INFO]: Biomes 1.12.0-SNAPSHOT-b159 (ENABLED)`
`[00:16:09] [Server thread/INFO]: BSkyBlock 1.13.0-SNAPSHOT-b612 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Challenges 0.9.0-SNAPSHOT-b404 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Chat 1.0.1 (ENABLED)`
`[00:16:09] [Server thread/INFO]: ControlPanel 1.7.0 (ENABLED)`
`[00:16:09] [Server thread/INFO]: DimensionalTrees 1.6.0 (ENABLED)`
`[00:16:09] [Server thread/INFO]: ExtraMobs 1.11.0.2 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Level 2.0.0-SNAPSHOT-b351 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Limits 1.9.5-SNAPSHOT-b208 (ENABLED)`
`[00:16:09] [Server thread/INFO]: Warps 1.9.0 (ENABLED)`

**Other comments**
Yesterday I updated the level addon and this problem was reported today by my users.

**Comment by BONNe** [comment]
There could be an error in config... (or in the console and log file).

**Comment by Blatower21** [comment]
@BONNe no, there is not error in console or log files. Level is calculated correctly, the only problem is /is value don't detecting any value.

**Comment by tastybento** [comment]
I'm still working on the 2.0.0-SNAPSHOT version. Thanks for the report. I haven't officially released this version yet.
