### ISSUE TITLE
/is top causes server lag

### ISSUE THREAD

**Issue by mikesonchan** [BentoBoxWorld/Level#154]
#### Describe the bug

/is top causes server lag.
#### Steps to reproduce the behavior

1. Execute /is top
#### Expected behavior

/is top shouldn't cause server lag.
#### Screenshots and videos (Optional)

https://www.youtube.com/watch?v=9jYlp7Luokc
##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.13.1
Database: JSON
Loaded Game Worlds:
ASkyBlock (BSkyBlock): Overworld, [nether_color]Nether, [end_color]End
Loaded Addons:
Biomes 1.7.0 (ENABLED)
BSkyBlock 1.13.1 (ENABLED)
Challenges 0.8.2 (ENABLED)
IslandFly 1.7.3 (ENABLED)
Level 2.0.0 (ENABLED)
Limits 1.12.2 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.9.5 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
Please run timings and do /is top and share the results so I can see what is lagging.

Also, if you do it again, does it lag again, or just the first time?

**Comment by mikesonchan** [comment]
https://timings.aikar.co/?id=df1e35850763461c8b59ccfd6966750b

If player executes /is top in a short period, it won't lag. But if player executes /is top after several hours, it will cause lag.

**Comment by tastybento** [comment]
I'll look into it. FYI, the timings report says you are using the wrong garbage collector for your server startup.
