### ISSUE TITLE
Essentials {Variable} (level placeholder) integration

### ISSUE THREAD

**Issue by BeastPsycho** [BentoBoxWorld/Level#156]
I would you add Essentials Level integration placeholder, for Skyblock showing Level variable in game chat
{bskyblocklevel} or {gamemodelevel} feature

**Comment by BONNe** [comment]
Sorry, but we cannot add that in essentials chat directly. Their API does not provide options like that.
However, you can use chat injector, that enables Placeholders API in it. https://bentobox-world.readthedocs.io/en/latest/BentoBox/Placeholders/#how-to-display-a-placeholder-in-the-chat
And bentobox uses papi placeholders: https://bentobox-world.readthedocs.io/en/latest/addons/Level/Placeholders/
