### ISSUE TITLE
Island Top

### ISSUE THREAD

**Issue by SoulDoesDrugs** [BentoBoxWorld/Level#160]
Seems to be an issue when running the command /is top, it works on the first go but after that gives errors, not sure how to go about posting them but you would like them I can make it happen.

**Comment by tastybento** [comment]
Do `/bbox version` in the console and share it.
Share what errors you see in the console here or screenshots or whatever.

**Comment by tastybento** [comment]
Have a look at #159 - might be a duplicate.
