### ISSUE TITLE
"/is top" shows wrong data

### ISSUE THREAD

**Issue by Espantonius** [BentoBoxWorld/Level#161]
#### Describe the bug
When showing the "/is top" the data it shows is wrong. It shows duplicate users who don't own the islands.

#### Steps to reproduce the behavior
Here is a top of an island:
https://prnt.sc/taq3t2

But that user is not the owner of that island:
https://prnt.sc/taq3xq

Another example. It looks like top but it is not the owner:
https://prnt.sc/taq3kl

Here the info of the island:
https://prnt.sc/taq3oz

By last. Some top are duplicated:
https://prnt.sc/taq5r0
https://prnt.sc/taq5mg

With the same owner:
https://prnt.sc/taq7i3

Is there something wrong or it's just me?

##### Output of `/bbox version` (Mandatory)

```
PAPER 1.15.2.
BentoBox version: 1.14.0-SNAPSHOT-b1811
Biomes 1.12.0-SNAPSHOT-b160 (ENABLED)
BSkyBlock 1.14.0-SNAPSHOT-b646 (ENABLED)
Challenges 0.9.0-SNAPSHOT-b418 (ENABLED)
Chat 1.1.0-SNAPSHOT-b28 (ENABLED)
ControlPanel 1.13.0-SNAPSHOT-b18 (ENABLED)
DimensionalTrees 1.6.1-SNAPSHOT-b81 (ENABLED)
Level 2.3.0-SNAPSHOT-b378 (ENABLED)
Limits 1.14.0-SNAPSHOT-b220 (ENABLED)
MagicCobblestoneGenerator 1.9.1-SNAPSHOT-b108 (ENABLED)
Warps 1.9.8-SNAPSHOT-b244 (ENABLED)
```

**Comment by tastybento** [comment]
Please try the latest build when it compiles.
