### ISSUE TITLE
WARNING /is level lag spike

### ISSUE THREAD

**Issue by Bricec6** [BentoBoxWorld/Level#168]
#### Describe the bug
We have huge lag spike when typing /is level on our islands, in version 1.13.1 (1.15.2) this command didn't cause any problem

#### Steps to reproduce the behavior
create a island
cmd: /is level

#### Expected behavior
It would be necessary to adjust the time loss at each /is level, we are on the VPS OVH https://www.ovh.com/fr/order/vps/?v=3#/vps/build?selection=~(range~'Comfort~pricingMode~'default~flavor~'vps-comfort-4-8-160~datacenters~(SBG~1))

if we have 3 / 5 players who make this command, the server will not support

#### Screenshots and videos (Optional)

![image](https://user-images.githubusercontent.com/51750055/87142797-5504ed00-c2a5-11ea-98d0-c38e28514c6c.png)

**Comment by tastybento** [comment]
Please update to the latest Level version 2.3.0.
