### ISSUE TITLE
Ability to have different block counts per gamemode

### ISSUE THREAD

**Issue by johncsuti** [BentoBoxWorld/Level#174]
#### Is your feature request related to a problem?

Kinda on my server I have AcidIsland, AOneBlock, BSkyBlock, and CaveBlock. Stone is worth 1 for island level. Thus on skyblock your level might be 10 but on CaveBlock your level is close to 100,000...

#### Describe the solution you'd like us to implement.

Ability to make different files with the name being the gamemode and use those values instead. Example:
BSkyBlock.yml > stone is worth 10 island level is 100
CaveBlock.yml > stone is worth 0 island level is 10

#### Describe alternatives you've considered.

None

### Additional context

N/A

**Comment by BONNe** [comment]
It is done per world in the same config file:
https://github.com/BentoBoxWorld/Level/blob/develop/src/main/resources/blockconfig.yml#L778
