### ISSUE TITLE
display the player’s island ranking on the server scoreboard

### ISSUE THREAD

**Issue by GrooveWJH** [BentoBoxWorld/Level#180]
### Description
I want to display the player’s island ranking on the server scoreboard. This problem may not be very deep. I have no experience with scoreboard. No relevant answer was found on Google. Please help me. Translated by Google, Origin :Chinese

**Comment by tastybento** [comment]
> There's actually no placeholders that return the island's rank.

And there can't be any because you can't reference such a thing. The answer is still the same, use the top ten placeholders available and prefix them with 1,2,3,4,5,6,7,8,9,10 as the rank in the scoreboard display.
