### ISSUE TITLE
Island Level Miscalculation

### ISSUE THREAD

**Issue by Weymouth87** [BentoBoxWorld/Level#181]
#### Describe the bug

**Copied straight from my message in discord**

One of our players, whilst offline his island value has over doubled. When you compare his data file to another user, who for example has the exact same amount of netherrack as him. In his file it shows a value of 53802, yet in theirs its 16621. But they have pretty much the same amount.

The second user has died significantly less than the first. And having calculated the values of their islands roughly, I cant see where there is an island level difference of almost 700 levels. The only difference between the players, is one has bought an island size expansion. They havent built anything in the expanded area, and air is worth 0 but thats the only thing thats obviously different.

The other weird thing, is both users have a high listed value for bedrock... Bedrock wasnt even in the levels file, and even when I added it to be worth zero, user 1:  "BEDROCK": 95249, user 2:  "BEDROCK": 26043.

Yet both users have 3 pieces of bedrock across their 3 islands? So how a. is this number different, and b. how does that correlate to their crazily different values as it happens for a number of blocks listed that they have equal amounts of?
#### Expected behavior

The island level calculation (value/100) doesnt seem to match up with the island levels being produced.

##### Output of `/bbox version` (Mandatory)

```
Warps 1.10.0 (ENABLED)
28.07 18:24:50 [Server] INFO TwerkingForTrees 1.4.1-SNAPSHOT-b46 (ENABLED)
28.07 18:24:50 [Server] INFO MagicCobblestoneGenerator 2.1.0-SNAPSHOT-b154 (ENABLED)
28.07 18:24:50 [Server] INFO Limits 1.14.0 (ENABLED)
28.07 18:24:50 [Server] INFO Level 2.3.4-SNAPSHOT-b403 (ENABLED)
28.07 18:24:50 [Server] INFO Greenhouses 1.2.0-SNAPSHOT-b242 (ENABLED)
28.07 18:24:50 [Server] INFO DimensionalTrees 1.6.1-SNAPSHOT-b81 (ENABLED)
28.07 18:24:50 [Server] INFO ControlPanel 1.13.0-SNAPSHOT-b38 (ENABLED)
28.07 18:24:50 [Server] INFO CheckMeOut 1.0.2 (ENABLED)
28.07 18:24:50 [Server] INFO Chat 1.1.0-SNAPSHOT-b30 (ENABLED)
28.07 18:24:50 [Server] INFO Challenges 0.8.4-SNAPSHOT-b428 (ENABLED)
28.07 18:24:50 [Server] INFO BSkyBlock 1.14.1-SNAPSHOT-b670 (ENABLED)
28.07 18:24:50 [Server] INFO Biomes 1.13.0-SNAPSHOT-b180 (ENABLED)
28.07 18:24:50 [Server] INFO Loaded Addons:
28.07 18:24:50 [Server] INFO bskyblock_world (BSkyBlock): Overworld, Nether, The End
28.07 18:24:50 [Server] INFO Loaded Game Worlds:
28.07 18:24:50 [Server] INFO Database: JSON
28.07 18:24:50 [Server] INFO BentoBox version: 1.15.0-SNAPSHOT-b1845
28.07 18:24:50 [Server] INFO Running PAPER 1.15.2.
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

I can provide my player files for examples if needed :)

**Comment by tastybento** [comment]
I suspect you have nether level calculation on. What is happening is the nether ceiling is adding to their level as it is being generated. This is was fixed recently. But upgrading will not fix it. 
There are a few options. Turn off Nether level calculations. Set netherrack to 0 value. Turn off nether ceiling.

**Comment by Weymouth87** [comment]
Thanks for the response, I made this change. Netherrack now has a value of zero, yet the island levels in question havent changed at all. I saved the config, reloaded then rebooted the server. The config edit stayed, just nothing in the island levels havent changed.

https://prnt.sc/tq42nj https://gyazo.com/a49c8b950cd6f74d8f9cd6217b026f56 

The two island levels in question: https://gyazo.com/b3b083f2789ce3ab2dd0bfa8d9ecf234

**Comment by tastybento** [comment]
They won't change value unless you recalculate the level by doing /island level (name) or /bsb level (name).

**Comment by Weymouth87** [comment]
I did, there was no difference :)

**Comment by tastybento** [comment]
By the way, use the console to run those commands because it will output a full report that explains how the calculation is done.

**Comment by tastybento** [comment]
Share the report so I can see what it is calculating for each island.

**Comment by Weymouth87** [comment]
28.07 22:43:14 [Server] INFO ==================================
28.07 22:43:14 [Server] INFO WATER: 1,044 blocks
28.07 22:43:14 [Server] INFO AIR: 10,482,727 blocks
28.07 22:43:14 [Server] INFO Total number = 10,483,771
28.07 22:43:14 [Server] INFO Blocks on island that are not in config.yml
28.07 22:43:14 [Server] INFO ==================================
28.07 22:43:14 [Server] INFO NETHERRACK: 52,802 blocks (max 1000)
28.07 22:43:14 [Server] INFO Blocks not counted because they exceeded limits: 52,802
28.07 22:43:14 [Server] INFO ==================================
28.07 22:43:14 [Server] INFO Subtotal = 142923
28.07 22:43:14 [Server] INFO REDSTONE_TORCH:1 blocks x 5 = 5
28.07 22:43:14 [Server] INFO GREEN_SHULKER_BOX:1 blocks x 11 = 11
28.07 22:43:14 [Server] INFO OAK_BUTTON:1 blocks x 1 = 1
28.07 22:43:14 [Server] INFO ANDESITE:1 blocks x 1 = 1
28.07 22:43:14 [Server] INFO GRANITE:1 blocks x 1 = 1
28.07 22:43:14 [Server] INFO ENCHANTING_TABLE:1 blocks x 150 = 150
28.07 22:43:14 [Server] INFO DAMAGED_ANVIL:1 blocks x 5 = 5
28.07 22:43:14 [Server] INFO YELLOW_SHULKER_BOX:1 blocks x 11 = 11
28.07 22:43:14 [Server] INFO BREWING_STAND:1 blocks x 20 = 20
28.07 22:43:14 [Server] INFO BLUE_SHULKER_BOX:1 blocks x 11 = 11
28.07 22:43:14 [Server] INFO PURPLE_SHULKER_BOX:1 blocks x 11 = 11
28.07 22:43:14 [Server] INFO LEVER:1 blocks x 1 = 1
28.07 22:43:14 [Server] INFO COBBLESTONE_SLAB:2 blocks x 1 = 2
28.07 22:43:14 [Server] INFO COBWEB:2 blocks x 10 = 20
28.07 22:43:14 [Server] INFO END_ROD:2 blocks x 1 = 2
28.07 22:43:14 [Server] INFO OAK_FENCE_GATE:2 blocks x 4 = 8
28.07 22:43:14 [Server] INFO PURPUR_STAIRS:2 blocks x 2 = 4
28.07 22:43:14 [Server] INFO WHITE_BED:2 blocks x 6 = 12
28.07 22:43:14 [Server] INFO COMPARATOR:2 blocks x 10 = 20
28.07 22:43:14 [Server] INFO SNOW:2 blocks x 1 = 2
28.07 22:43:14 [Server] INFO OBSERVER:3 blocks x 1 = 3
28.07 22:43:14 [Server] INFO FURNACE:3 blocks x 8 = 24
28.07 22:43:14 [Server] INFO IRON_BARS:3 blocks x 2 = 6
28.07 22:43:14 [Server] INFO SEA_PICKLE:3 blocks x 1 = 3
28.07 22:43:14 [Server] INFO NETHER_WART:4 blocks x 1 = 4
28.07 22:43:14 [Server] INFO FIRE:4 blocks x 0 = 0
28.07 22:43:14 [Server] INFO CRAFTING_TABLE:4 blocks x 1 = 4
28.07 22:43:14 [Server] INFO STONE_BRICK_STAIRS:5 blocks x 2 = 10
28.07 22:43:14 [Server] INFO MAGMA_BLOCK:5 blocks x 1 = 5
28.07 22:43:14 [Server] INFO SPAWNER:5 blocks x 0 = 0
28.07 22:43:14 [Server] INFO OAK_SIGN:5 blocks x 6 = 30
28.07 22:43:14 [Server] INFO NETHER_PORTAL:6 blocks x 1 = 6
28.07 22:43:14 [Server] INFO OAK_SLAB:6 blocks x 1 = 6
28.07 22:43:14 [Server] INFO COBBLESTONE_STAIRS:6 blocks x 2 = 12
28.07 22:43:14 [Server] INFO ICE:6 blocks x 5 = 30
28.07 22:43:14 [Server] INFO HOPPER:7 blocks x -10 = -70
28.07 22:43:14 [Server] INFO REDSTONE_BLOCK:7 blocks x 10 = 70
28.07 22:43:14 [Server] INFO OAK_PRESSURE_PLATE:8 blocks x 2 = 16
28.07 22:43:14 [Server] INFO SOUL_SAND:8 blocks x 2 = 16
28.07 22:43:14 [Server] INFO END_PORTAL:9 blocks x 0 = 0
28.07 22:43:14 [Server] INFO PISTON_HEAD:9 blocks x 1 = 9
28.07 22:43:14 [Server] INFO GRAVEL:9 blocks x 1 = 9
28.07 22:43:14 [Server] INFO NETHER_QUARTZ_ORE:10 blocks x 1 = 10
28.07 22:43:14 [Server] INFO LAVA:10 blocks x 0 = 0
28.07 22:43:14 [Server] INFO END_PORTAL_FRAME:12 blocks x 0 = 0
28.07 22:43:14 [Server] INFO CHISELED_STONE_BRICKS:12 blocks x 2 = 24
28.07 22:43:14 [Server] INFO DIAMOND_BLOCK:13 blocks x 300 = 3900
28.07 22:43:14 [Server] INFO REPEATER:14 blocks x 6 = 84
28.07 22:43:14 [Server] INFO LADDER:16 blocks x 2 = 32
28.07 22:43:14 [Server] INFO NETHER_BRICK_FENCE:17 blocks x 2 = 34
28.07 22:43:14 [Server] INFO SAND:20 blocks x 1 = 20
28.07 22:43:14 [Server] INFO OAK_STAIRS:20 blocks x 2 = 40
28.07 22:43:14 [Server] INFO OAK_DOOR:20 blocks x 2 = 40
28.07 22:43:14 [Server] INFO MELON:20 blocks x 1 = 20
28.07 22:43:14 [Server] INFO EMERALD_BLOCK:22 blocks x 150 = 3300
28.07 22:43:14 [Server] INFO PUMPKIN:23 blocks x 1 = 23
28.07 22:43:14 [Server] INFO SMOOTH_STONE:24 blocks x 1 = 24
28.07 22:43:14 [Server] INFO CRACKED_STONE_BRICKS:25 blocks x 2 = 50
28.07 22:43:14 [Server] INFO BOOKSHELF:26 blocks x 5 = 130
28.07 22:43:14 [Server] INFO MOSSY_STONE_BRICKS:26 blocks x 2 = 52
28.07 22:43:14 [Server] INFO END_STONE_BRICKS:27 blocks x 2 = 54
28.07 22:43:14 [Server] INFO WALL_TORCH:29 blocks x 1 = 29
28.07 22:43:14 [Server] INFO CACTUS:30 blocks x 1 = 30
28.07 22:43:14 [Server] INFO CHEST:36 blocks x 8 = 288
28.07 22:43:14 [Server] INFO GOLD_BLOCK:37 blocks x 150 = 5550
28.07 22:43:14 [Server] INFO TORCH:37 blocks x 1 = 37
28.07 22:43:14 [Server] INFO OBSIDIAN:38 blocks x 10 = 380
28.07 22:43:14 [Server] INFO KELP:44 blocks x 1 = 44
28.07 22:43:14 [Server] INFO OAK_TRAPDOOR:48 blocks x 3 = 144
28.07 22:43:14 [Server] INFO STONE:52 blocks x 1 = 52
28.07 22:43:14 [Server] INFO END_STONE:58 blocks x 1 = 58
28.07 22:43:14 [Server] INFO STICKY_PISTON:60 blocks x 1 = 60
28.07 22:43:14 [Server] INFO STONE_BRICKS:60 blocks x 2 = 120
28.07 22:43:14 [Server] INFO OAK_LOG:62 blocks x 0 = 0
28.07 22:43:14 [Server] INFO SUGAR_CANE:65 blocks x 1 = 65
28.07 22:43:14 [Server] INFO NETHER_BRICKS:65 blocks x 2 = 130
28.07 22:43:14 [Server] INFO COBBLESTONE_WALL:77 blocks x 1 = 77
28.07 22:43:14 [Server] INFO IRON_BLOCK:113 blocks x 10 = 1130
28.07 22:43:14 [Server] INFO REDSTONE_WIRE:132 blocks x 1 = 132
28.07 22:43:14 [Server] INFO MYCELIUM:156 blocks x 5 = 780
28.07 22:43:14 [Server] INFO FARMLAND:289 blocks x 1 = 289
28.07 22:43:14 [Server] INFO KELP_PLANT:293 blocks x 1 = 293
28.07 22:43:14 [Server] INFO GRASS_BLOCK:563 blocks x 4 = 2252
28.07 22:43:14 [Server] INFO BIRCH_PLANKS:687 blocks x 1 = 687
28.07 22:43:14 [Server] INFO OAK_LEAVES:698 blocks x 0 = 0
28.07 22:43:14 [Server] INFO GLASS:1,003 blocks x 2 = 2006
28.07 22:43:14 [Server] INFO WATER:1,043 blocks x 0 = 0
28.07 22:43:14 [Server] INFO DIRT:2,197 blocks x 3 = 6591
28.07 22:43:14 [Server] INFO COBBLESTONE:2,739 blocks x 1 = 2739
28.07 22:43:14 [Server] INFO OAK_PLANKS:5,334 blocks x 1 = 5334
28.07 22:43:14 [Server] INFO GLOWSTONE:10,049 blocks x 1 = 10049
28.07 22:43:14 [Server] INFO NETHERRACK:53,802 blocks x 0 = 0
28.07 22:43:14 [Server] INFO BEDROCK:95,249 blocks x 1 = 95249
28.07 22:43:14 [Server] INFO AIR:10,482,726 blocks x 0 = 0
28.07 22:43:14 [Server] INFO Total number of blocks = 10,658,381
28.07 22:43:14 [Server] INFO Regular block count
28.07 22:43:14 [Server] INFO ==================================
28.07 22:43:14 [Server] INFO New level = 1388
28.07 22:43:14 [Server] INFO Previous level = 1388
28.07 22:43:14 [Server] INFO Initial island level = -33
28.07 22:43:14 [Server] INFO Deaths handicap = 8
28.07 22:43:14 [Server] INFO Level cost = 100
28.07 22:43:14 [Server] INFO Formula to calculate island level: blocks / level_cost
28.07 22:43:14 [Server] INFO Total block value count = 142,923

Its counting 94,000+blocks of bedrock. Yet theres no bedrock in the vaules file and when i add it with a value of zero it deletes itself when I reboot the server or reload the plugin?

**Comment by tastybento** [comment]
Do a search in your blockconfi.yml file for BEDROCK. It's probably in there at the bottom maybe with a value of 1.
 Like mine:
```
  ZOMBIE_HEAD: 1
  ZOMBIE_WALL_HEAD: 1
  BEDROCK: 0
  BEACON: 1
  BEE_NEST: 1
  BEEHIVE: 1
```

**Comment by Weymouth87** [comment]
Ah my apologies! I didnt twig that bedrock was listed at the bottom! Island level dropped by 900, worked like a charm thank you!
