### ISSUE TITLE
Island Top losing players

### ISSUE THREAD

**Issue by Ac3dUd3** [BentoBoxWorld/Level#187]
#### Describe the bug
when I first added it, it was working fine, over time it seems to be degrading to now only showing 5 people total, not even the top island holder (their rank is 65k or something)

#### Steps to reproduce the behavior
/is top

#### Expected behavior
show correct is top

#### Screenshots and videos (Optional)
http://prntscr.com/ua3inq

##### Output of `/bbox version` (Mandatory)
>....=>.... [04:05:00 INFO]: Running PAPER 1.16.1.
>.... [04:05:00 INFO]: BentoBox version: 1.14.2
>.... [04:05:00 INFO]: Database: MARIADB
>.... [04:05:00 INFO]: Loaded Game Worlds:
>.... [04:05:00 INFO]: lockupislands (lockupislands): Overworld
>.... [04:05:00 INFO]: Loaded Addons:
>.... [04:05:00 INFO]: Biomes 1.13.0-SNAPSHOT-b181 (ENABLED)
>.... [04:05:00 INFO]: Border 1.0.9 (ENABLED)
>.... [04:05:00 INFO]: BSkyBlock 1.14.0 (ENABLED)
>.... [04:05:00 INFO]: Challenges 0.8.3 (ENABLED)
>.... [04:05:00 INFO]: Chat 1.0.5 (ENABLED)
>.... [04:05:00 INFO]: ControlPanel 1.7.0 (ENABLED)
>.... [04:05:00 INFO]: DimensionalTrees 1.6.0 (ENABLED)
>.... [04:05:00 INFO]: ExtraMobs 1.11.0.3 (ENABLED)
>.... [04:05:00 INFO]: Greenhouses 1.2.0 (ENABLED)
>.... [04:05:00 INFO]: Level 2.4.1 (ENABLED)
>.... [04:05:00 INFO]: Likes 2.1.0-SNAPSHOT-b29 (ENABLED)
>.... [04:05:00 INFO]: Limits 1.14.0 (ENABLED)
>.... [04:05:00 INFO]: MagicCobblestoneGenerator 2.1.0 (ENABLED)
>.... [04:05:00 INFO]: MagicSummon 1.5.0.0 (ENABLED)
>.... [04:05:00 INFO]: TwerkingForTrees 1.4.1 (ENABLED)
>.... [04:05:00 INFO]: VoidPortals 1.5.0.0 (ENABLED)
>.... [04:05:00 INFO]: Warps 1.10.0 (ENABLED)
```
_______

 
### Additional context (Optional)
<!-- Any additional information you'd like to provide us. -->
<!-- Please type below this line. -->
I run a prison server so i expect the island levels to get quite high due to the high ore count

**Comment by tastybento** [comment]
Huh, weird. You're using MariaDB, so this might be a bit difficult, but I'd like to look at your `TopTenData` database table and `IslandLevels` table. Can you export them, zip them up, and share them? You should be able to drag and drop zip files to these response boxes.

**Comment by Ac3dUd3** [comment]
[data-dump.zip](https://github.com/BentoBoxWorld/Level/files/5166183/data-dump.zip)
I am unsure how to get those specific tabled so I got the dump of the whole bentobox database, hope that is ok

**Comment by tastybento** [comment]
Okay, thanks. I'll have to look at this over the weekend. It does look like your levels tables has plenty of islands in there that should be in the top ten. I'm not sure why they are not in there. I also will plan to make an admin command to rebuild the top ten.

**Comment by tastybento** [comment]
Please try 2.4.2 snapshot on ci.bentobox.world when it is available.

**Comment by Ac3dUd3** [comment]
Hi mate, tried the snapshot and it worked for about 3 minutes then the islands top player disappeared. the best seem to be there. is it because the level is too high at 65k?

**Comment by tastybento** [comment]
No, the level is stored in a long, which is a very very large integer. 

Does the top player have the `bskyblock.intopten` perm active? https://docs.bentobox.world/en/latest/addons/Level/Permissions/
