### ISSUE TITLE
IslandLevelCalculatedEvent returns wrong level

### ISSUE THREAD

**Issue by bertek41** [BentoBoxWorld/Level#189]
#### Describe the bug
When i do /cave level it returns 100 but in IslandLevelCalculatedEvent it returns 25731.

#### Steps to reproduce the behavior
/cave level

#### Expected behavior
It should return 100 like /cave level returns.

#### Screenshots and videos (Optional)
![image](https://user-images.githubusercontent.com/20637793/92760448-53d16880-f399-11ea-8fda-1d3818720480.png)

##### Output of `/bbox version` (Mandatory)
```
Running PAPER 1.16.2.
BentoBox version: 1.15.0-SNAPSHOT-b1853
Database: JSON
Loaded Game Worlds:
caveblock-world (caveblock): Overworld, Nether*, The End*
Loaded Addons:
Biomes 1.13.0-SNAPSHOT-LOCAL (ENABLED)
Border 2.0.0 (ENABLED)
CaveBlock 1.15.1-SNAPSHOT-b363 (ENABLED)
Chat 1.1.0-SNAPSHOT-b33 (ENABLED)
ControlPanel 1.13.0-SNAPSHOT-b41 (ENABLED)
ExtraMobs 1.11.0.4-SNAPSHOT-b7 (ENABLED)
Level 2.4.1 (ENABLED)
Likes 2.1.0-SNAPSHOT-b29 (ENABLED)
Limits 1.15.0-SNAPSHOT-b228 (ENABLED)
MagicCobblestoneGenerator 2.2.0-SNAPSHOT-LOCAL (ENABLED)
TwerkingForTrees 1.4.1-SNAPSHOT-b47 (ENABLED)
Upgrades 0.2.0-SNAPSHOT-b64 (ENABLED)
Warps 1.10.1-SNAPSHOT-LOCAL (ENABLED)
```

### Additional context (Optional)
```
@EventHandler
public void onBentoBoxEvent(BentoBoxEvent event) {
	Map<String, Object> keyValues = event.getKeyValues();
	if("IslandLevelCalculatedEvent".equals(event.getEventName())) {
		UUID uniqueId = (UUID) keyValues.get("targetPlayer");
		getServer().broadcastMessage("IslandLevelCalculatedEvent#getLevel: "+keyValues.get("level"));
	}
}
```

[IslandLevels.zip](https://github.com/BentoBoxWorld/Level/files/5207892/IslandLevels.zip)

**Comment by tastybento** [comment]
The initial island level was not being subtracted from the level. Try the latest snapshot and let me know if that works for you.

**Comment by bertek41** [comment]
Tested build 415 and interestingly problem persists.

**Comment by tastybento** [comment]
What does your config.yml look like? Do you have:

```
# Zero island levels on new island or island reset
# If true, Level will calculate the starter island's level and remove it from any future level calculations.
# If false, the player's starter island and will count towards their level.
# This will reduce CPU if it isn't used.
zero-new-island-levels: false
```

in it?

**Comment by bertek41** [comment]
Yes its set to true

**Comment by tastybento** [comment]
Hmm, try build 416. This works for me. Here's my result:

```
[11:29:06 INFO]: BoxManager issued server command: /cb
[11:29:51 INFO]: BoxManager issued server command: /is level
[11:29:58 INFO]: [BentoBox] DEBUG: IslandLevelCalculatedEvent#getLevel: 20
```
<img width="502" alt="Screen Shot 2020-09-12 at 11 31 24 AM" src="https://user-images.githubusercontent.com/4407265/93002381-7ffcfe80-f4eb-11ea-9e3e-ec464feb7b9d.png">

**Comment by tastybento** [comment]
[Post deleted] I used the wrong command.

**Comment by tastybento** [comment]
Bug replicated... working on a fix now.

**Comment by bertek41** [comment]
Current build set my island level to initial level. But my server is not public rn so np.

**Comment by tastybento** [comment]
This new build should work. I tested it with your listener and get what's expected. It actually was a long-standing bug where the initial level wasn't being used.

**Comment by bertek41** [comment]
Yep its working now thank you.
