### ISSUE TITLE
Island values gui

### ISSUE THREAD

**Issue by ChimpGamer** [BentoBoxWorld/Level#192]
#### Is your feature request related to a problem?

At the moment it is not possible to for players to see which blocks have the most value.

#### Describe the solution you'd like us to implement.

This could be solved by adding a GUI that shows the block values in a nice way. The GUI should be sorted from highest value to lowest value.

**Comment by OverBrave** [comment]
It seems almost 2 years have passed since the feature request, is there any enhancement soon?

**Comment by BONNe** [comment]
Implemented the wrong thing.
Request was for displaying `/[player_cmd] values` as GUI
