### ISSUE TITLE
Cache Island Level Values

### ISSUE THREAD

**Issue by IsXGeo** [BentoBoxWorld/Level#201]
### Description
Its very annoying to always have to wait for a calculation to be run on your island. Especially if the Island has a large border and is relatively empty.

#### Describe the solution you'd like us to implement.
I'd like for an option that stores an online players island level somewhere (a file, or ram) and updates that level whenever they place a block and/or periodically recalculate that players island level.

Then after that player has been disconnected for an amount of time, save that value somewhere for /is top or discard it. Then when the player rejoins add the recalculation to the queue.

Personally, having to have my islands value recalculated every time I run a command isn't a great solution. Especially when someone is lazy and instead of scrolling up in the chat they re-run the command.

Caching the value would be good for that as well because if a player is placing or breaking blocks and such to determine how much their island value increases or decreases, recalculating the value each time is inefficient. It would be simpler to add or remove the value of each block by a cached total each time. Or atleast I think that its more efficient personally. I could easily be incorrect.

Thanks anyways for considering and reading my feature request.

**Comment by BONNe** [comment]
The reason why it is not done with block placing and breaking is related to the fact that tasty afraid of incorrectly detecting if block is placed or broken. 
In general, events should be reliable, however, under server lag or using plugins that manipulate blocks may affect values, even if it should not.

However, I agree that Level addon should use this, even with "incorrect" detections. It could be like an approximate value, but exact will be calculated only on command call.

**Comment by tastybento** [comment]
If the problem that is trying to be solve is to give a player their island level if they have just calculated it then it could be added to the cool down message. They could get the last-know level for then next 10 minutes or whatever the cool down is.
