### ISSUE TITLE
Island name placeholders

### ISSUE THREAD

**Issue by charlyg31** [BentoBoxWorld/Level#211]
#### Is your feature request related to a problem?

Add new placeholders for top 10 island,
i need to add %bskyblock_island_name% for top 10 with %bskyblock_island_name_#RANK#%

Thanks.

**Comment by tastybento** [comment]
Isn't that already available? https://docs.bentobox.world/en/latest/addons/Level/Placeholders/

**Comment by charlyg31** [comment]
it is the name of the owner of the island which is currently displayed, it would be good to be able to put the name of the island which one gives with a / is setname

**Comment by organizatsiya** [comment]
Hello,
it already exists: 

`%[gamemode]_island_name% | Name of the island | 1.4.0`

**Comment by charlyg31** [comment]
> Hello,
> it already exists:
> 
> `%[gamemode]_island_name% | Name of the island | 1.4.0`

Is not for top 10.

**Comment by tastybento** [comment]
Duplicate of #132
