### ISSUE TITLE
Excluded users in top

### ISSUE THREAD

**Issue by kFxDaKing** [BentoBoxWorld/Level#213]
Hello, would be good if you add excluded-users, for example admins that wont be seen in top.

Something like this 
![image](https://user-images.githubusercontent.com/52855882/108492158-19072100-72a5-11eb-9a0e-efff5ed4fcfe.png)

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/Level#permissions
Just remove permission which allows being in top10.
