### ISSUE TITLE
AdvancedChests compatibility

### ISSUE THREAD

**Issue by Kesims** [BentoBoxWorld/Level#214]
#### Is your feature request related to a problem?
Hello, would it be possible to add compatibility for AdvancedChests? Island level counts blocks in normal chests, but it does not work for chests created by AdvancedChests. 

#### Describe the solution you'd like us to implement.
Add support for AdvancedChests, so its content would be counted as well.

### Additional context

link to plugins site on spigot: https://www.spigotmc.org/resources/%E2%AD%90advancedchests%E2%AD%90-unlimited-sizes-holograms-%E2%9C%A8upgrades-%E2%9C%85sells-%E2%9A%A1sorter-%E2%98%84%EF%B8%8F-compressor.79061/

link to API:  https://github.com/DeadSilenceIV/AdvancedChestsAPI

**Comment by tastybento** [comment]
The developer is working on an enhancement to the API to enable async operation.

**Comment by tastybento** [comment]
Okay, I don't have the actual plugin so I can't test it, so have a go [with the latest snapshot](https://ci.codemc.io/job/BentoBoxWorld/job/Level/) and let me know if it works. You will need to set the config to can chests:
```
# Include chest contents in level calculations.
# Will count blocks in chests or containers.
include-chests: true
```
The console should say "Hooking in to AdvancedChests" on startup and it should count all the items in the chest. Let me know what happens.

**Comment by Kesims** [comment]
Hello,  I have "Hooking in to AdvancedChests" in console, that is right. But when I run /is level, it never finishes. When I try again, it says "Island level calculation is in progress...", so there is probbably something wrong. 
I can buy you the plugin so you can test it yourself :)

**Comment by tastybento** [comment]
If you turn off the chest scanning in the config does the calculation come back pretty quickly?

**Comment by tastybento** [comment]
The plug-in would be useful. I am tastybento (at) BentoBox (dot) world.

**Comment by Kesims** [comment]
Yes, when I turn off chests calculation, it returns level in few seconds

**Comment by Kesims** [comment]
I have sent you the plugin jar to your email.

**Comment by tastybento** [comment]
Hmmm, I didn't receive anything. Could you try again or send to tastybento @ wasteofplastic.com?

**Comment by Kesims** [comment]
2nd try, sent to both mails, hope it arrives. Mby mail blocked it because it contained jar file, so I sent you link to my google drive to download it from there.

**Comment by tastybento** [comment]
Got it!

**Comment by tastybento** [comment]
This is now working. It requires the latest version of AdvancedChests 14.3. This was provided to me for testing by the developer.

**Comment by Kesims** [comment]
Oh, yeah, atm I had only 14.2, 14.3 wasnt released yet on spigot. Thank you for implementing this, its just awesome..! :)
