### ISSUE TITLE
Placeholder: %Level_[gamemode]_top_rank%

### ISSUE THREAD

**Issue by Teyir** [BentoBoxWorld/Level#215]
**Description**
Hey,

can you add this new placeholder just for return the rank.
Exemple my player is not on the top ten, if I use the placeholder I can have the real rank, example 24.

Or juste add a new line with our rank when we make /is top
![image](https://user-images.githubusercontent.com/60007549/109416188-f7045180-79bc-11eb-8d76-4956fbe32b56.png)

(just under my level)

**Placeholder**: `%Level_[gamemode]_top_rank%`

Thank you very much

**Comment by tastybento** [comment]
The rank of the player is shown in the top ten now as well as the island level so players can see where they are.

**Comment by Teyir** [comment]
Thank you very much
