### ISSUE TITLE
Is top bug

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Level#22]
_From @Frozen-Craft on October 15, 2018 16:12_

**Describe the bug**
Island appear twice in topten

**To Reproduce**
The bug seems appear when a player give make another player owner
(and the island level change)

**Expected behavior**
there is some bugs with islands owner and others island ranks please fix them

**Screenshots**
https://imgur.com/a/B0Vyocc

**Server Information (please complete the following information):**
 - Database being used: Flat file
 - OS: Linux
 - Java Version: Java 8
 - Other plugins? LuckPerms, WorldEdit, SkyGUI, EggCatcher, CustomOreGen, MinewebBridge, PlugMan, AdvancedBan, ProtocolLib, WorldGuard, HideAndCustomPlugins, VoidGenerator, BentoBox, VoxelSniper, AdvancedBanGUI, TAB, CS-CoreLib, Vault, Essentials, EpicRename, QuickShop, Multiverse-Core, Citizens, VanishNoPacket, MythicMobs, Slimefun, EssentialsChat, Shop, EssentialsSpawn, DungeonsXL, CrateReloaded

_Copied from original issue: BentoBoxWorld/bentobox#307_

**Comment by tastybento** [comment]
@Poslovitch Is this still a bug?

**Comment by Poslovitch** [comment]
I don't know. I just moved the issue there a while ago.

**Comment by BONNe** [comment]
Hmm, if it is Island Top, then it is a bug...
If it is a player top... then it is not a bug

**Comment by wellnesscookie** [comment]
Umm, well if it was a player top, I would expect all of the members on the list without any need of passing leader to others.

**Comment by tastybento** [comment]
This is fixed, but you'll need the latest 1.3.0+ BentoBox to use it. I recommend waiting for that to be officially released unless you like living on the edge!

**Comment by wellnesscookie** [comment]
**BBox version output:**
```
[10:40:33] [main/INFO]: [CHAT] Running PAPER 1.13.2.
[10:40:33] [main/INFO]: [CHAT] BentoBox version: 1.4.0-SNAPSHOT
[10:40:33] [main/INFO]: [CHAT] Loaded Game Worlds:
[10:40:33] [main/INFO]: [CHAT] skyblock (skyblock)
[10:40:33] [main/INFO]: [CHAT] Loaded Add-Ons
[10:40:33] [main/INFO]: [CHAT] Biomes 0.5.0-SNAPSHOT
[10:40:33] [main/INFO]: [CHAT] BSkyBlock 1.3.0-SNAPSHOT
[10:40:33] [main/INFO]: [CHAT] Challenges 0.6.0
[10:40:33] [main/INFO]: [CHAT] Level 1.2.2-SNAPSHOT
[10:40:33] [main/INFO]: [CHAT] SerbCraftAddon 2.0
[10:40:33] [main/INFO]: [CHAT] WelcomeWarps 1.2.1-SNAPSHOT
```
**Duplications found:**
1. http://prntscr.com/mwq78p
2. http://prntscr.com/mwq7j3

**Additional context:**
- Bump: Last 4 builds seem not have /is value implemented, as the ingame output says the command is unknown, but I see a merged commit for it overthere. Was it on purpose or shall we open an issue for it?

**Comment by tastybento** [comment]
@wellnesscookie Please open a new ticket and refer to closed ones. It's really had to find your comments otherwise.

I think this is a duplicate of #50 .
For /is value - it's not launched yet, but I just merged into develop, so maybe you'll see it become available.
