### ISSUE TITLE
Blackstone appears twice in this file

### ISSUE THREAD

**Issue by user670** [BentoBoxWorld/Level#222]
https://github.com/BentoBoxWorld/Level/blob/452bf88197566a0d6f2ee16ce0c3b6569b457b69/src/main/resources/blockconfig.yml#L46

https://github.com/BentoBoxWorld/Level/blob/452bf88197566a0d6f2ee16ce0c3b6569b457b69/src/main/resources/blockconfig.yml#L80

blackstone twice? Also iirc YAML doesn't allow duplicated keys?

**Comment by tastybento** [comment]
Thanks. Yes, the one lower down would have overwritten the values above it.

**Comment by user670** [comment]
> Thanks. Yes, the one lower down would have overwritten the values above it.

Um, actually you should be thankful that you have a less strict YAML parser. iirc YAML standards **forbids** duplicate keys, and some parsers actually throw an error if you have duplicate keys.
