### ISSUE TITLE
[Feature] Add support for RoseStacker

### ISSUE THREAD

**Issue by ThatOneTree** [BentoBoxWorld/Level#226]
#### Is your feature request related to a problem?
No

#### Describe the solution you'd like us to implement.
Add support for RoseStacker stacked blocks to count towards levels. It is a fairly popular stacker plugin and is up to date.

#### Describe alternatives you've considered.
N/A

### Additional context
N/A

**Comment by tastybento** [comment]
I'm working with the developer on this.
