### ISSUE TITLE
Placeholder: level_bskyblock_rank_value

### ISSUE THREAD

**Issue by Novasky-Guy** [BentoBoxWorld/Level#238]
**Description**

Would i be possible to downgrade this placeholder to version 2.6.4? so that older version of the plugin can use it without having to completely upgrade minecraft version.
**Placeholder**: `level_bskyblock_rank_value`

**Comment by tastybento** [comment]
If you can use Java 16, then I think this should be possible with the BentoBox v1.16.5 release. The latest Level snapshot on ci.bentobox.world should work.
