### ISSUE TITLE
1.18.1 Support

### ISSUE THREAD

**Issue by Chtholly** [BentoBoxWorld/Level#247]
### Expected behavior

Please add support for new heights in Minecraft 1.18.1

### Observed/Actual behavior

Blocks that are build under Y-0 and over Y-256 will not calculatet to the island-level

### Steps/models to reproduce

-

### BentoBox version

BentoBox 1.19.0
AOneBlock 1.9.0.

**Comment by tastybento** [comment]
Yes, this just got done. It's in the snapshot version on ci.bentobox.world. I'll do a release this weekend.

**Comment by tastybento** [comment]
See release 2.9.0
