### ISSUE TITLE
getChunkSnapshot in IslandLevelCalculator cause an Accessing PalettedContainer from multiple threads exception

### ISSUE THREAD

**Issue by Pirgosth** [BentoBoxWorld/Level#256]
### Expected behavior

When running the /island level command we expect the actual island level to be displayed.

### Observed/Actual behavior

Instead the server randomly crashed and a really weird exception occured, blocking all server threads and causing the server not to respond until a manual restart.

### Steps/models to reproduce

Hard to tell, run /is level sometimes make it.

Here is a stacktrace and memory dump of the actual bug: [https://pastebin.com/688sENCT](https://pastebin.com/688sENCT)

### BentoBox version

[18:07:13] [Server thread/INFO]: Serveur SPIGOT Invalide.
[18:07:13] [Server thread/INFO]: Version de BentoBox : 1.18.0
[18:07:13] [Server thread/INFO]: Base de données : JSON
[18:07:13] [Server thread/INFO]: Mondes de jeu chargés :
[18:07:13] [Server thread/INFO]: skyblock (SkyBlock) : Overworld, Nether, End
[18:07:13] [Server thread/INFO]: Addons chargés :
[18:07:13] [Server thread/INFO]: Biomes 1.14.0 (ENABLED)
[18:07:13] [Server thread/INFO]: Border 3.2.0 (ENABLED)
[18:07:13] [Server thread/INFO]: BSkyBlock 1.15.2 (ENABLED)
[18:07:13] [Server thread/INFO]: Challenges 0.8.4 (ENABLED)
[18:07:13] [Server thread/INFO]: ControlPanel 1.13.0 (ENABLED)
[18:07:13] [Server thread/INFO]: DimensionalTrees 1.6.0 (ENABLED)
[18:07:13] [Server thread/INFO]: Level 2.8.1 (ENABLED)
[18:07:13] [Server thread/INFO]: Limits 1.17.2 (ENABLED)
[18:07:13] [Server thread/INFO]: Warps 1.11.1 (ENABLED)

### Plugin list

Plugins (23): LuckPerms, WorldBorderAPI, LibertyCore, Vault, ProtocolLib, WorldEdit, SkinsRestorer, ChestCommands, BentoBox, Essentials, EssentialsChat, LibertyHub, TAB, Multiverse-Core, WorldGuard, XClaim, EssentialsDiscord, Multiverse-Inventories, AuthMe, Multiverse-NetherPortals, SkyShop, WorldChatPrefix, OreGenerator

### Other

I'm not sure if this is related to your plugin, it seem like it come from spigot or minecraft, but I can't find anything online related to the 1.18.1.. (Only old topics about an old bug in minecraft code itself, but from 2019..)

I don't know either why the `bbox version` tells my spigot version is invalid (maybe because 1.18 is still not supported) but in case here is my spigot version: `This server is running CraftBukkit version 3412-Spigot-862678e-0d109e8 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)`

**Comment by BONNe** [comment]
There is BentoBox update 1.19 that is considering Minecraft 1.18.1, but it does not affect the Level addon snapshot issue.

**Comment by Pirgosth** [comment]
Yes i saw that, for performance issues when using /is reset I now use latest dev build, we will see if this remains.

I don't know if somebody else managed to get this issue, but it's a really bad one

**Comment by tastybento** [comment]
Yes, this is a bug. The chunk snapshot is being taken in an asynchronous thread task. This used to be okay but was not really allowed. Clearly it now is not okay or risky and I'll need to rewrite some of the code to avoid this. I'm out of the country right now so I can't work on this immediately but I'll make it a priority when I get back.

**Comment by Pirgosth** [comment]
Okay I get it, for the moment I think I'll prevent the usage of this command, feel free to ask if I can give it some help!

**Comment by tastybento** [comment]
This should work now. I'll push out a release shortly.
