### ISSUE TITLE
CaveBlock Island Level Miscalculations

### ISSUE THREAD

**Issue by PuppetMasterZee** [BentoBoxWorld/Level#258]
### Expected behavior

Player creates new cave, then executes the /cave level command.  It should return a 0 cave level for a new untouched cave.

### Observed/Actual behavior

Problem occurs when player creates new cave, then executes the /cave level command.  It returns a level which may be excessively high or excessively low.  Player has not interacted with the cave (ie no mining or placing blocks.) When rechecking the level, the it begins to decrease and continues to do so when rechecked.  Even when player places high level blocks the cave level continues to decrease upon each recheck (level rechecked at varying intervals.)  Occurs when using default BentoBox cave generation.

### Steps/models to reproduce

Link to recording of error.
[https://youtu.be/NvGDgANHSJo]

### BentoBox version

BentoBox v1.20.1 (snapshot)

server version: paper 1.18.2-310
bentobox version: 1.20.1
level addon version: 2.9.1 (tested also 2.9.0) (default config)
caveblock version: 1.15.0 (default config)
installed addons: [bank, border, caveblock, challenges, chat, controlpanel, extramobs, islandrankup, level, limits,twerkingfortrees,visit]

### Plugin list

Plugins list
[https://imgur.com/a/jWrN8iK]

**Comment by BONNe** [comment]
> We are using default islands with default config.

I think I got something:
Can you run the command: `cave level <player>` from the console 2 times with a bit of delay between them?

It will print out the "blocks" that are calculated for the level.

**Comment by BONNe** [comment]
So, a fast fix would be to disable the bedrock roof in caveblock config file:
https://github.com/BentoBoxWorld/CaveBlock/blob/7bbcd40df2429739a51496d861d9d203b67d2bee/src/main/resources/config.yml#L101

Apperantly, CaveBlock started to generate dirt and grass_block layer at the top of the world bellow bedrock block. As the bedrock is above grass block, it turns into dirt and that is the reason why it decreases cave level.

**Comment by BONNe** [comment]
@tastybento I am sorry, this is not Level addon issue.
This is CaveBlock issue. I will solve it in next caveblock verison.

**Comment by BONNe** [comment]
I pushed a new CaveBlock version that should fix the "dropping" level.

The issue was with the new world generation, as it generated grass blocks below the top bedrock layer. And as the world updates and grass blocks become dirt, every player lost a lot of levels.

This, however, would require regenerating caveblock world as the top of the world would contain 5 dirt layers.

https://ci.codemc.io/job/BentoBoxWorld/job/CaveBlock/420/
