### ISSUE TITLE
 support for the latest api of Advanced Chest

### ISSUE THREAD

**Issue by jack444410** [BentoBoxWorld/Level#265]
### Expected behavior

Island level should count the item value inside the chest

![image](https://user-images.githubusercontent.com/72694726/178118571-93527c5f-e6c9-4ca6-a12c-a0a7c8771c56.png)

### Observed/Actual behavior

with that option enabled, the item in chest should be counted.
but it still only count the blocks which is placed in the island

### Steps/models to reproduce

do things above

### BentoBox version

![image](https://user-images.githubusercontent.com/72694726/178118648-555e97b0-b147-4367-8602-dfc95331959d.png)

**Comment by BONNe** [comment]
I have no idea how to use their new API. So the most likely scenario is to drop Advanced Chests until someone figures out how to use it.

**Comment by DeadSilenceIV** [comment]
Hello i've opened a pull request to solve this issue in particular.
[https://github.com/BentoBoxWorld/Level/pull/266](url)

**Comment by BONNe** [comment]
> Hello i've opened a pull request to solve this issue in particular. #266

Thanks. I still do not get why it is made via WildCards? 
Any particular reason?

**Comment by DeadSilenceIV** [comment]
Hello and thanks for the interest, Since the new API of AdvancedChests adds the possibility of having multiple kinds of chests, it required the use of WildCards to structure some classes in a easier way.
