### ISSUE TITLE
Placeholder support

### ISSUE THREAD

**Issue by Zenya4** [BentoBoxWorld/Level#27]
Is there a placeholder for chat formatting (EssentialsX) for this level addon?

**Comment by Poslovitch** [comment]
Yes, but that'll need some boilerplate code. But that's possible .

**Comment by Poslovitch** [comment]
More and more users are asking for this.
@tastybento Registering a placeholder can be done using this code:
```java
BentoBox.getInstance().getPlaceholdersManager().registerPlaceholder(Addon, String, PlaceholderReplacer);
```
See [the Javadoc](https://ci.codemc.org/job/BentoBoxWorld/job/BentoBox/javadoc/world/bentobox/bentobox/managers/PlaceholdersManager.html) for reference.

**Comment by tastybento** [comment]
@Poslovitch Thanks. I'll look into this now.

**Comment by tastybento** [comment]
Okay, added in commit 8eaca607d8894bb626d16b55744396140337615b
It needs testing.

**Comment by tastybento** [comment]
Added these placeholders:

**Level Placeholder**
%Level_island-level% - the player's level

**Top Ten Placeholders**
%Level_island-level-top-value-**x**% where **x** is a number between 1 and 10
%Level_island-level-top-name-**x**% where **x** is a number between 1 and 10

If the top ten is less than 10 players then the placeholder will return an empty string.

Tested using Placeholder API's parse command and they work.

e.g.
>papi parse LSPVicky level %Level_island-level-top-value-10%
[21:37:20 INFO]: level 
>papi parse LSPVicky level %Level_island-level-top-value-1%
[21:37:23 INFO]: level 28
>papi parse LSPVicky level %Level_island-level%
[21:37:38 INFO]: level 28

**Comment by tastybento** [comment]
commit 97fb4342449902d1b332b282bac9253db0d570ef

**Comment by tastybento** [comment]
Note placeholder names now have the game mode in them so you can get them for any game mode.
