### ISSUE TITLE
Add a command to view the number of certain blocks placed on the player's island

### ISSUE THREAD

**Issue by CuteLittleSky** [BentoBoxWorld/Level#273]
### Is your feature request related to a problem?

Level has the ability to calculate the number of cube levels but the player has no way of knowing if they have reached that number.

### Describe the solution you'd like.

Add/bsb level block command to see the number of certain blocks placed by the player

### Describe alternatives you've considered.

Add a command to view the number of certain blocks placed on the player's island

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
If you do `/is value` then a GUI pops up showing all the blocks and count on your island. Is this what you are looking for?

**Comment by BONNe** [comment]
Tastybento, value menu shows the value of blocks in the gamemode.

He wants a detail menu that is available when clicking on bottom icon when viewing top islands.

**Comment by CuteLittleSky** [comment]
> If you do `/is value` then a GUI pops up showing all the blocks and count on your island. Is this what you are looking for?

Yes, because there is a limit on the maximum number of levels a single block can add to the island level, so that players know how many blocks they have placed.

**Comment by tastybento** [comment]
The number of blocks placed and the limits have been available in the GUI (via the /is top command) forever, but this adds the info to the `/is value hand` command as well.
