### ISSUE TITLE
Command to add level points to an island

### ISSUE THREAD

**Issue by PakArmy99** [BentoBoxWorld/Level#280]
### Is your feature request related to a problem?

A command that when executed would give x points to a player's island. This could be used for the challenge addon. For example, upon completing a challenge, this command could be executed to give a certain amount of points to the user.

### Describe the solution you'd like.

A command like /bsb level give [player] X
Where X are the points you want to give

### Describe alternatives you've considered.

---

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
This duplicates #236

**Comment by PakArmy99** [comment]
Sorry, i didnt see that x.x
