### ISSUE TITLE
Generic top or stats feature for server management.

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/Level#293]
### Is your feature request related to a problem?

No, not really related to a problem, besides the problem of trying to manage a server. 

### Describe the solution you'd like.

It would be quite fantastic to have the ability to have some sort of bbox stats or bbox top command that is global. Which helps with gathering up some information that helps the server owner get an insight into the world(s) that they run. This to help with server management. We have some unlocks for levels, top islands, that give perms, perms, features, and advancements. And we have to manually glance ingame and run manual commands to see the top players, their values, island values of active players, etc. It would be quite nice if we could get a glimpse into what most island levels linger around, how quickly players might reset or have how well the average values are for islands, like "most islands are around 100 levels, top islands around 1000" so we know not to require 1000 mini island level and creative an exclusive club. 

On discord I mentioned this, so copy pasting that here:

is there a way to see how many people have certain island levels, like
"/oneblockadmin level islands list 100"
-> found 17 islands with less than 100 island levels
-> found 211 islands with more than 100 island levels
or some /oneblockadmin topblock sort
-> top 10...
-> page 2: summery of islands less than 50, 100, 250, 500, 1000, 1500

To get some sort of impression of how people generally are doing?
we have some unlock perk and features and perms things that we base on min island level and it's kinda nice to see over time if we have to lower or raise those values based on the averages and top island values etc.

### Describe alternatives you've considered.

installing more and more addons that give specific information like topblock for oneblock.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

Thank you for considering

**Comment by tastybento** [comment]
@mrfloris I've added a stats command. You can run it with any admin command, e.g., `oba stats` or `acid stats` and it'll give results for all the worlds on the server. You can run it in-game but it may be best viewed in the console if you have a lot of worlds. Let me know what you think. https://ci.codemc.io/job/BentoBoxWorld/job/Level/
