### ISSUE TITLE
Placeholder: %aoneblock_island_members_count_top_value_X%

### ISSUE THREAD

**Issue by Jimaie72** [BentoBoxWorld/Level#294]
**Description**

Hello, I want to create the following calculation:
- Island level divided by the number of members

So I use : %math_{Level_aoneblock_top_value_1}/{aoneblock_island_members_count}%

{aoneblock_island_members_count} = return for the island of player but not for example for the 1st value.

I actually want to create an average in order to balance between an island with a single member and an island with 4 members.

**Placeholder**: `%aoneblock_island_members_count_top_value_X%`

**Comment by tastybento** [comment]
How about I just give you a placeholder where the island level is divided by the number of players on the team? We could call it `%aoneblock_island_weighted_top_value_1%`, `%aoneblock_island_weighted_top_value_2%`, etc?

**Comment by Jimaie72** [comment]
Oh yes, perfect !!

**Comment by tastybento** [comment]
@Jimaie72 This is done. The new placeholders are `%Level_[gamemode]_top_weighted_value_x%` where x is 1 to 10.

**Comment by Jimaie72** [comment]
I need : %Level_aoneblock_top_weighted_name_1% 

Because %Level_aoneblock_top_name_1% it's for %Level_aoneblock_top_value_1%
