### ISSUE TITLE
Placeholder: %Level_aoneblock_top_weighted_name_x%

### ISSUE THREAD

**Issue by Jimaie72** [BentoBoxWorld/Level#296]
**Description**

Thank fort he new placeholders are %Level_[gamemode]_top_weighted_value_x% where x is 1 to 10.

I need : %Level_aoneblock_top_weighted_name_1%

Because %Level_aoneblock_top_name_1% it's for %Level_aoneblock_top_value_1%

**Placeholder**: `%Level_aoneblock_top_weighted_name_x%`

**Comment by tastybento** [comment]
Okay:

`%Level_[gamemode]_top_weighted_name_x%`
`%Level_[gamemode]_top_weighted_members_x%`
`%Level_[gamemode]_top_weighted_island_name_x%`
`%Level_[gamemode]_top_weighted_value_x%`
