### ISSUE TITLE
Levels - List Customizability

### ISSUE THREAD

**Issue by BrotherHateCN** [BentoBoxWorld/Level#302]
### Is your feature request related to a problem?

Players on my server would wish for a cleaner level top/value/detail GUI. However as there are no external placeholders for calculating amount of blocks placed on a set "Island", creating an external GUI just would not work well. Players have asked that I remove values that are irrelevant e.g buttons, leaves (the ones with value of 0) - however, today I found out it is not possible. As also removing values from blockconfig (as they just come back after a reload).

### Describe the solution you'd like.

I would like the ability to remove specific block types from blockconfig fully so that Value and in Detail GUI can be customized properly (e.g if I only want to show ORE Blocks and spawners - this isn't possible as it replaces the item name/desc with default value e.g acacia leaves).

### Describe alternatives you've considered.

Considered using:
"This button is available in detail_panel and value_panel. This button shows given material as icon.

Example:

  #icon: STONE
  title: level.gui.buttons.value.name
  description: level.gui.buttons.value.description
  data:
    type: BLOCK
"
This didn't seem to work as hoped

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
I think this may be best done by adding more tabs that you can then use (or not). Right now the tabs are:

- All Blocks - lists every block counted, even Air, and so it's not that useful
- Above sea level - this is mainly for AcidIsland
- Below sea level - same - for AcidIsland
- Spawners - I don't think this is very useful

What tabs would you like? I can suggest adding a tab to show scored blocks only - only lists blocks that are worth something. Anything else?

**Comment by BONNe** [comment]
Maybe just a filter button that would hide all items with default or zero value?

**Comment by BrotherHateCN** [comment]
Hi, sorry for the late response.


And perhaps something like BONNEe said, 
But in general I wish I could just set the blocks that appear. In the customization I can remove the "Sort By" and just keep the default "all blocks" but in this section, upon request of my players, they wish to only see the blocks that actually count. Which in my case is ore blocks, e.g diamond block etc and or Blocks with custom NBT (if not possible yet) as specific spawners cannot be created to add value.

**Comment by rudde0** [comment]
> Maybe just a filter button that would hide all items with default or zero value?

I think this is very needed feature. I only give points to mine blocks and for this reason most of the blocks are existing for nothing in GUI.
