### ISSUE TITLE
Request for Additional Placeholders and Sign Functionality 

### ISSUE THREAD

**Issue by mrWezyr** [BentoBoxWorld/Level#311]
### Is your feature request related to a problem?

no

### Describe the solution you'd like.

Would like to request additional placeholders for the level calculation:
**Owner-only island level:** Calculate the island level only for the player who owns the island, not for the island team members.
Alternatively, add the functionality of using placeholders on signs.

### Describe alternatives you've considered.

Currently, I'm using an addon for showing placeholders on signs, but it doesn't work very well.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

I like using signs for scoreboards, and I use ajLeaderboards. When I use the placeholder "Island level of the player's island," all players from the same island appear in the first place on the scoreboard.

**Comment by tastybento** [comment]
The level is calculated for the island itself, so it should be the same for every player on the island. Have a look at https://docs.bentobox.world/en/latest/addons/Level/#placeholders for the list. Or can you explain more what you want?

**Comment by mrWezyr** [comment]
Hey,
Sure, here is an example:
I'm using %Level_[gamemode]_island_level% for the leaderboard. Island team members are included in this leaderboard, and I don't want them to be visible.
![javaw_vZrJ8cxUjP](https://github.com/BentoBoxWorld/Level/assets/38501324/8afaf65e-4ab3-4b8d-800e-ecdbe4282763)
I want to be able to use %Level_[gamemode]_top_value_<number>% on a sign without needing any other plugins (since vanilla Minecraft doesn't support placeholders on signs).

**Comment by tastybento** [comment]
Why don't you use `%Level_[gamemode]_top_name_x%` where x is the top ten number? 

Also you wrote:

> I'm using %Level_[gamemode]island_level% for the leaderboard. Island team members are included in this leaderboard, and I don't want them to be visible.

`%Level_[gamemode]_island_level%` gives a number - the level of the island. What placeholder are you using to get the **name** of the player? I recommend the above placeholder for a leaderboard - that is what they are for.

**Comment by tastybento** [comment]
@mrWezyr bump ^^^^

**Comment by mrWezyr** [comment]
Hey sorry for late respond 
The main problem is with the ajleaderboard plugin, which automatically assigns player names to the placeholder. If the placeholder counts points for all players (including island members), this problem arises.
Using
%Level_[gamemode]top_name<number>% and %Level_[gamemode]_top_value_<number>%
in combination with another plugin for displaying the placeholder on signs works fine. I would like to see this functionality integrated with the bentobox plugin

**Comment by tastybento** [comment]
@mrWezyr This is done in that you can use the `%Level_[gamemode]_island_level_owner%` placeholder. That will give the island level for the owner only and 0 for everyone else (so they will be at the bottom of the top list). I tested on ajleaderboard and it works. Just register that placeholder and then make the top ten signs.

**Comment by tastybento** [comment]
In looking at ajleaderboard I can see how it would add players because it is tracking the
