### ISSUE TITLE
POSSIBILITY TO REMOVE BLOCKS FROM THE LIST

### ISSUE THREAD

**Issue by Aides123** [BentoBoxWorld/Level#324]
### Is your feature request related to a problem?

Overall, yes, this is a problem.
You can't remove blocks from the list because it automatically adds them, and even if I set the value to 0 it still displays them in the GUI which is problema

### Describe the solution you'd like.

I would like it to be possible to set myself which blocks should be counted, and the rest to be removed.

### Describe alternatives you've considered.

I would like it to be possible to set myself which blocks should be counted, and the rest to be removed.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
The latest version shows only blocks with value by default. 

I'll try and think of a way to hide blocks too.

**Comment by Aides123** [comment]
![image](https://github.com/user-attachments/assets/56f3c97a-792e-4260-b643-377c9cd63119)
I set the value of the blocks 0 of those it does not want, and they continue to display.

**Comment by Aides123** [comment]
Level-2.15.0

**Comment by tastybento** [comment]
I added section that hides the blocks in the section:

```
# These blocks will never be shown in the GUI even if they have value
 hidden-blocks:
   - BEDROCK
   - AIR
```
Please try the latest snapshot.

**Comment by Aides123** [comment]
I just tested and it continues to show blocks in the gui.
![image](https://github.com/user-attachments/assets/6372b209-0c4d-4792-951a-49f0e540f327)

**Comment by Aides123** [comment]
https://pastebin.com/FnRUdFpS

**Comment by Aides123** [comment]
version: [#585](https://ci.codemc.io/job/BentoBoxWorld/job/Level/585/)

**Comment by BONNe** [comment]
You need space before `-` in your listings.

**Comment by Aides123** [comment]
Default config 
![image](https://github.com/user-attachments/assets/a5a6da89-b11b-46f5-ad32-3541f8182dda)


> You need space before `-` in your listings.

**Comment by tastybento** [comment]
Ah, I apologize, I misunderstood that this was about the `/is top` island view, and not the Value panel. I've added that support now, so blocks should no longer be shown in the value panel either.

**Comment by BONNe** [comment]
ahahha :D
