### ISSUE TITLE
Add beacon to the default block scores as well

### ISSUE THREAD

**Issue by TheOne-Player** [BentoBoxWorld/Level#336]
### Is your feature request related to a problem?

Not related to a problem.

### Describe the solution you'd like.

In blockconfig, set a default value for BEACON block.

### Describe alternatives you've considered.

I could modify this for just my server, however, I feel like the beacon is a valuable block and not including any block points for having it (by default) isn't something that most players like.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
Good idea [351318e](https://github.com/BentoBoxWorld/Level/commit/351318ef9fe5ffc4c665e4d54cd6eb7162a03c74)
