### ISSUE TITLE
Console error when changing world name

### ISSUE THREAD

**Issue by doitliketyler** [BentoBoxWorld/Level#34]
**Description**
If I change my world name from the default "AcidIsland_world" name everything works fine except I get this error in the console or startup:

[ERROR] [BentoBox] Level Addon: No such world : AcidIsland_world

**Steps to reproduce the behavior:**
1. Change world name
2. Restart server
3. Read console

**Expected behavior**
For there to be no error in the console.

**Server Information:**
- Database: Flat file
 - OS: Debian
 - Java Version: 8
 - BentoBox version: Latest
 - Addons installed? All of them

**Comment by tastybento** [comment]
@BONNe 's right. Look in the Level add-on's config.yml at the bottom. There's a set of block value definitions that reference the world. You need to change the world name there too.

We can look into changing this so that it references game mode addons instead of worlds.

**Comment by doitliketyler** [comment]
That's exactly what is what. Thanks for getting back to me so fast.
