### ISSUE TITLE
Nether Island Level

### ISSUE THREAD

**Issue by eri6640** [BentoBoxWorld/Level#40]
Is it already possible to somehow enable level calculation in nether and maybe end world too?
This would be really good feature.

**Comment by x1p** [comment]
I can confirm that Nether & End island do not add up to the level.

This is highly wishful as players want to build a Nether or End island.

If this won't add up to the level calculation, the no one will build there.

Please, consider adding those worlds.

**Comment by 4c5458** [comment]
It's not an enhancement, it's rather a bug! It should be default behavior.

**Comment by tastybento** [comment]
Not a bug, by design (my design), I never included the Nether or End. It was not in ASkyBlock either. I do acknowledge that it's a request and should be possible. We've made a lot of enhancements to async block counting so it's not I'm not so worried about lag anymore.

**Comment by wellnesscookie** [comment]
Yes, but since people got probably used or adapted to only overworld level calculation - it should definitely be toggleable

**Comment by BONNe** [comment]
Awesome would be if you could group worlds.

F.e. group all gamemode worlds, so it shows a single level overall server :D

**Comment by wellnesscookie** [comment]
Well, indeed, but there should also exist placeholder for each world and one that sums them all up in one.

Are you willing to implement placeholders? 😂

**Comment by thunderlight411** [comment]
it will be nice if this can be added,
Got some questions of my players who are asked why the nether and the end not calculated in the island level

**Comment by tastybento** [comment]
Yep, I totally understand. Part of the history here was that ASkyBlock originally had the standard nether so it never happened. What people would do would be that they'd go to the nether, harvest blocks and bring them back to the overworld where they would count. Anyway, enough history, it's in the plan.

**Comment by Tomvapor** [comment]
Hey, great idea.
Im looking for is level implement for nether and end too. Thanks for adding to 1.6.0

**Comment by tastybento** [comment]
Okay, done. Note that as islands are zero-leveled when they are created, current players will see a jump in their island level if you enable this mid-game (about 47 levels using default config) because all the nether blocks and end blocks will suddenly be counted. For new players or resets, their islands will be correctly zeroed at start.
As there's no way of knowing what players started with I cannot retroactively zero islands, so it'll just be a bonus for current players. :-)
