### ISSUE TITLE
Negative level calculated

### ISSUE THREAD

**Issue by GonzoDark** [BentoBoxWorld/Level#41]
**Description**
The problem is that the BSkyblock levels are calculated wrong.

**Steps to reproduce the behavior:**
Using the command /island level

**Expected behavior**
I expected to see positive levels (level 17?)

**Console dump** (Using the command "/bsbadmin user GonzoDark")
10.02 20:38:39 [Server] INFO Calculating level...
**_10.02 20:38:39 [Server] INFO Island level is -449_**
10.02 20:38:39 [Server] INFO Level Log for island in BSkyBlock at 0,120,0
10.02 20:38:39 [Server] INFO Island owner UUID = 31a89138-24bd-44da-aa33-b5e50d54a3f6
10.02 20:38:39 [Server] INFO Total block value count = 1,712
10.02 20:38:39 [Server] INFO Level cost = 100
10.02 20:38:39 [Server] INFO Deaths handicap = 0
**_10.02 20:38:39 [Server] INFO Level calculated = 17_**
10.02 20:38:39 [Server] INFO ==================================
10.02 20:38:39 [Server] INFO Regular block count
10.02 20:38:39 [Server] INFO Total number of blocks = 2,085
10.02 20:38:39 [Server] INFO OAK_PLANKS:864 blocks x 1 = 864
10.02 20:38:39 [Server] INFO COBBLESTONE:239 blocks x 1 = 239
10.02 20:38:39 [Server] INFO JUNGLE_LEAVES:237 blocks x 0 = 0
10.02 20:38:39 [Server] INFO VINE:147 blocks x 1 = 147
10.02 20:38:39 [Server] INFO JUNGLE_LOG:99 blocks x 0 = 0
10.02 20:38:39 [Server] INFO SPRUCE_LEAVES:95 blocks x 0 = 0
10.02 20:38:39 [Server] INFO BIRCH_LEAVES:58 blocks x 0 = 0
10.02 20:38:39 [Server] INFO SPRUCE_LOG:53 blocks x 0 = 0
10.02 20:38:39 [Server] INFO WATER:52 blocks x 0 = 0
10.02 20:38:39 [Server] INFO FARMLAND:30 blocks x 1 = 30
10.02 20:38:39 [Server] INFO DIRT:28 blocks x 3 = 84
10.02 20:38:39 [Server] INFO GRASS_BLOCK:25 blocks x 4 = 100
10.02 20:38:39 [Server] INFO TORCH:23 blocks x 1 = 23
10.02 20:38:39 [Server] INFO BIRCH_PLANKS:19 blocks x 1 = 19
10.02 20:38:39 [Server] INFO SUGAR_CANE:11 blocks x 1 = 11
10.02 20:38:39 [Server] INFO CACTUS:11 blocks x 1 = 11
10.02 20:38:39 [Server] INFO ATTACHED_MELON_STEM:8 blocks x 1 = 8
10.02 20:38:39 [Server] INFO LADDER:8 blocks x 2 = 16
10.02 20:38:39 [Server] INFO CHEST:8 blocks x 8 = 64
10.02 20:38:39 [Server] INFO PODZOL:8 blocks x 2 = 16
10.02 20:38:39 [Server] INFO MELON:8 blocks x 1 = 8
10.02 20:38:39 [Server] INFO WHEAT:8 blocks x 1 = 8
10.02 20:38:39 [Server] INFO PUMPKIN_STEM:8 blocks x 1 = 8
10.02 20:38:39 [Server] INFO SAND:6 blocks x 1 = 6
10.02 20:38:39 [Server] INFO BIRCH_LOG:6 blocks x 0 = 0
10.02 20:38:39 [Server] INFO PUMPKIN:5 blocks x 1 = 5
10.02 20:38:39 [Server] INFO WALL_TORCH:5 blocks x 1 = 5
10.02 20:38:39 [Server] INFO ATTACHED_PUMPKIN_STEM:5 blocks x 1 = 5
10.02 20:38:39 [Server] INFO WALL_SIGN:4 blocks x 6 = 24
10.02 20:38:39 [Server] INFO LAVA:2 blocks x 0 = 0
10.02 20:38:39 [Server] INFO MELON_STEM:1 blocks x 1 = 1
10.02 20:38:39 [Server] INFO FURNACE:1 blocks x 8 = 8
10.02 20:38:39 [Server] INFO BEDROCK:1 blocks x 0 = 0
10.02 20:38:39 [Server] INFO CRAFTING_TABLE:1 blocks x 1 = 1
10.02 20:38:39 [Server] INFO POTTED_POPPY:1 blocks x 1 = 1
10.02 20:38:39 [Server] INFO Subtotal = 1712
10.02 20:38:39 [Server] INFO ==================================
10.02 20:38:39 [Server] INFO Blocks not counted because they exceeded limits: 0
10.02 20:38:39 [Server] INFO ==================================
10.02 20:38:39 [Server] INFO Blocks on island that are not in config.yml
10.02 20:38:39 [Server] INFO Total number = 0
10.02 20:38:39 [Server] INFO ==================================

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): []
YAML
Ubuntu 18.04
 - Java Version: [e.g. Java 8]
Java 8
 - BentoBox version: [e.g. 1.7.2.21]
1.2.1
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
SkyGrid 0.0.1-SNAPSHOT
AcidIsland 1.0
BSkyblock 1.1
Challenges 0.5.0-SNAPSHOT
Level 0.2.0
 - Other plugins? [Do '/plugins' and copy/paste from the console]
Plugins (22): CoreProtect, Wild, WorldEdit, FastAsyncWorldEdit, GameAPI, FlashlightPlus, Essentials, CommandHelper, PermissionsEx, Boss, mcMMO, Vault, WorldGuard, ProtocolLib, BentoBox, PerWorldInventory, PlotSquared, PreciousStones, Multiverse-Core, ChatControl, Multiverse-NetherPortals, CoreArena

**Additional context**
None

**Comment by tastybento** [comment]
I'm not sure how that happened, but it appears to be that the membership of the island does not include the owner. I'm not sure why that would be the case. I've added some defensive code but it looks like the island data may be a bit corrupted.

**Comment by GonzoDark** [comment]
So does that mean that you are working on a fix?

And is there anything I can do other than regenerating my island (which might make the same bug appear at some point in the future).

**Comment by tastybento** [comment]
I don’t have enough information as to how the database corrupted so I am blocked. 

Is this a team island? Or are you the only owner?

**Comment by tastybento** [comment]
Fixed. Thanks for the report.
The negative number was coming from a misapplied initial island level value (most likely from another world).
