### ISSUE TITLE
Get level from IslandLevelCalculatedEvent level does not match actual level

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/Level#43]
To get island level:

`Math.toIntExact((long)(new AddonRequestBuilder()).addon("Level").label("island-level").addMetaData("player", uuid).addMetaData("world-name", world).request());`

(It matches with /is level)

To get island level from event:

`Math.toIntExact((long) event.getKeyValues().get("level"));`

Island level from event shows 2 or 3 more levels.

Island: 0.2.0
Database: yml

**Comment by tastybento** [comment]
Should work with commit ddbe806af5d58cf00ba5f79d68d35325644d35c4. Please check.

**Comment by YellowZaki** [comment]
Yep, now it works perfect.
Thanks!
