### ISSUE TITLE
Island levels problem

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Level#44]
**Description**
If the player has 3 islands and restarts the island, the score of the other islands falls.

**Screenshots**
https://cdn.discordapp.com/attachments/310623455462686720/548031190993600512/island.mp4

**Server Information:**

* Database being used (YAML, JSON, MySQL, MongoDB, MariaDB): YAML
* OS: Linux
* Java Version: JAVA 8
* BentoBox version: Last Snapshot version
* Addons installed?
  ![image](https://user-images.githubusercontent.com/47111280/53149323-6a00b380-35be-11e9-95ac-df34a93538a5.png)

**Comment by tastybento** [comment]
Fixed. Thanks for the report.
