### ISSUE TITLE
The commands "/bsb top" and "/acid top" do not display the top ten player list

### ISSUE THREAD

**Issue by HuJunwei23333** [BentoBoxWorld/Level#45]
**Description**
Typing the commands "/bsb top" and "/acid top" cannot be displayed in the top 10 players in the chat bar.

**Steps to reproduce the behavior:**
1. Type the command '/bsb top'
2. But will output '/bsbadmin top: show the top ten list'

**Expected behavior**
I can use it in previous versions, I want to use this feature to do the top ten list of holograms.

**Screenshots**
![qul3c_vc j 2e_hpb j qlf](https://user-images.githubusercontent.com/30760975/53154320-76543300-35f5-11e9-9dfe-66cc60f0dbcd.png)

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [YAML]
 - OS: [Windows 7]
 - Java Version: [Java 8]
 - BentoBox version: [last Stable Build]
 - Addons installed? [[16:24:48 INFO]: Running SPIGOT 1.13.2.
[16:24:48 INFO]: BentoBox version: 1.3.0-SNAPSHOT
[16:24:48 INFO]: Loaded Game Worlds:
[16:24:48 INFO]: AcidIsland_world (AcidIsland)
[16:24:48 INFO]: BSkyBlock_world (BSkyBlock)
[16:24:48 INFO]: Loaded Addons:
[16:24:48 INFO]: AcidIsland 1.3.0-SNAPSHOT
[16:24:48 INFO]: BSkyBlock 1.3.0-SNAPSHOT
[16:24:48 INFO]: Biomes 0.5.0-SNAPSHOT
[16:24:48 INFO]: Challenges 0.6.0-SNAPSHOT
[16:24:48 INFO]: Level 1.2.1-SNAPSHOT
[16:24:48 INFO]: Limits 0.1.0-SNAPSHOT
[16:24:48 INFO]: WelcomeWarps 1.2-SNAPSHOT]
 - Other plugins? [[16:25:18 INFO]: Plugins (22): LuckPerms, WorldEdit, VoidGenerator, PlaceholderA
PI, HackedServer, SQLibrary, Vault, PlayerPoints, WorldGuard, Citizens, BentoBox
, React, CMIEInjector, ExtraContexts, Multiverse-Core, Residence, CMI, LocketteP
ro, BossShopPro, PlayerShops, ItemShops, GuiShopManager]

**Additional context**

**Comment by BONNe** [comment]
You should reset Level 1.2.1 configuration.

Level addon by default is disabled in all game modes.
To enable you should reset its configuration or add following lines:

`# GameModes
# Level will hook into these game modes. Don't forget to set any world-specific
# block values below!
game-modes:
- AcidIsland
- BSkyBlock
- CaveBlock`

**Comment by HuJunwei23333** [comment]
> You should reset Level 1.2.1 configuration.
> 
> Level addon by default is disabled in all game modes.
> To enable you should reset its configuration or add following lines:
> 
> ```
> # Level will hook into these game modes. Don't forget to set any world-specific
> # block values below!
> game-modes:
> - AcidIsland
> - BSkyBlock
> - CaveBlock
> ```

Old version configuration file has been deleted

**Comment by HuJunwei23333** [comment]
> You should reset Level 1.2.1 configuration.
> 
> Level addon by default is disabled in all game modes.
> To enable you should reset its configuration or add following lines:
> 
> ```
> # Level will hook into these game modes. Don't forget to set any world-specific
> # block values below!
> game-modes:
> - AcidIsland
> - BSkyBlock
> - CaveBlock
> ```

Old version configuration file has been deleted

**Comment by wellnesscookie** [comment]
No, I think this is the problem, please read the latest comment. 
https://github.com/BentoBoxWorld/Level/issues/22

**Comment by HuJunwei23333** [comment]
> I think this is the problem, please read the latest comment #22

Yes, I can use HolographicDisplays+Holographic Extension to make the hologram support PlaceholderAPI and then use **Top Ten Placeholders**
%Level_bskyblock-island-level-top-value-**x**% where **x** is a number between 1 and 10
%Level_bskyblock-island-level-top-name-**x**% where **x** is a number between 1 and 10

**Comment by tastybento** [comment]
Fixed. Thanks for the report.
