### ISSUE TITLE
Trying to get the top ten.

### ISSUE THREAD

**Issue by poma123** [BentoBoxWorld/Level#46]
Hi.
I'm trying to get the top ten from the Level addon in my plugin. My plan was to list the top 10 islands' owners and levels to the chat, when I run a command. But I can't figure out how should I do that.
I've tried few things:
```java
TopTen topten = ((Level) bentoBox.getAddonsManager().getAddonByName("Level").get()).getTopTen();
```
_java.lang.NoClassDefFoundError: world/bentobox/level/Level_

````java
Addon lvl = bentoBox.getAddonsManager().getAddonByName("Level").get();

Method mthd = lvl.getClass().getMethod("getTopTen");

TopTen topten = (TopTen) mthd.invoke(lvl);
````
_java.lang.ClassNotFoundException: world.bentobox.level.TopTen_

So the question is; how shall I do this?

Thanks in advance for your reply.

**Comment by BONNe** [comment]
No,
you should use Addon Request Handler:
https://github.com/BentoBoxWorld/BentoBox/pull/400

For level addon it is:
` ` `           
            What we need in the map:
            0. "world-name" -> String
            1. "player" -> UUID
            What we will return:
            - 0L if invalid input/player has no island
            - the island level otherwise (which may be 0)
```

**Comment by BONNe** [comment]
You should use PAPI

Placeholders ;)

**Comment by Poslovitch** [comment]
@BONNe Placeholders won't work if he want to get access to the TopTen instance for programmatic use.

For reference, addons classes cannot be accessed by plugins. That's a Java language specification. Either use the AddonRequestHandlers or create an addon.

**Comment by poma123** [comment]
So if I would like to do this with AddonRequestHandlers, I have to loop all the island levels and sort the list?
Because as I saw there are only an `island-level` handler in the Level addon.

**Comment by Poslovitch** [comment]
@tastybento will probably help you better than I can.

**Comment by tastybento** [comment]
Thanks @BONNe I think your PR should enable this.

**Comment by BONNe** [comment]
So, to get Top 10 players you should use Addon Request Handler.
https://github.com/BentoBoxWorld/BentoBox/pull/400

As input you should add `world-name` and in output you will get Map that contains UUID and Long (player and its island level)

**Comment by poma123** [comment]
Now working, thanks a lot!
