### ISSUE TITLE
Issus when adding last challenges and last level update of buento box

### ISSUE THREAD

**Issue by dryter97** [BentoBoxWorld/Level#49]
Weird GUI issus occure when adding challenges and level with buentobox skyblock. I can precisly say looking like some part of the code showing up. for my part i have simply test without level and working fine. still i need level on my server for the simple advancement purpose. im adding you a screen shop of issus occuring im prety sure its because a code line is not close or maybe something more advance than what i know. i wish you know what's the issus.

there is a discord

[https://media.discordapp.net/attachments/351818427301625857/551958636914540574/unknown.png?width=862&height=485](url)

**Comment by tastybento** [comment]
It looks like your locale files are out of date or not there. Try going into the BentoBox plugin folder and deleting the locale folder and then restart.

**Comment by BONNe** [comment]
By looking on image, i can definatly say, that locales are out of date. 
And it is Challenges addon locales, that must be updated.
