### ISSUE TITLE
Add {island-level} placeholder to Essentials chat

### ISSUE THREAD

**Issue by MorkaZ** [BentoBoxWorld/Level#54]
I have noticed that there was {island-level] variable in Askyblock's levels but now this variable does not works. I think it should be added because a lot of servers were using it.

**Comment by Poslovitch** [comment]
Use PlaceholderAPI and ChatInjector. These variables weren't added back to BentoBox as we were having a lot of issues with them.

**Comment by johncsuti** [comment]
This would not work correctly as essentials uses the end players island level to replace all the placeholders in chat use something else besides essentials chat as it doesn't play nicely.

Using luckperms with chat control seems to work the best and seems to play very nicely with bentobox as a whole.

**Comment by tastybento** [comment]
Agreed (unfortunately).
