### ISSUE TITLE
Request for /is top

### ISSUE THREAD

**Issue by IGDT** [BentoBoxWorld/Level#55]
**Is your feature request related to a problem? Please describe.**
A small problem, the players heads in /is top has color codes which we can't change.
Now it's &e&o<playername> and it would be nice to be able to change that in the config

**Describe the solution you'd like**
Adding an extra feature in the config file to edit the color codes of a players head in /is top

**Describe alternatives you've considered**
I am not sure which any other alternative solution there is for this "problem"

**Additional context**
![image](https://user-images.githubusercontent.com/36332464/57403773-b2ea0080-71da-11e9-9af5-c57721e06106.png)

**Comment by tastybento** [comment]
@IGDT This is already supported in the locale files so I'm confused. Am I missing something?
