### ISSUE TITLE
Island top data

### ISSUE THREAD

**Issue by ronc617** [BentoBoxWorld/Level#62]
TopTen Data file name is being saved as Upper case
It also does not seem to hold the current IS Top data
reverts to old data instead of current

![image](https://user-images.githubusercontent.com/36974241/60575059-dd72b880-9d48-11e9-8cc3-83150c2ef5de.png)

Running SPIGOT 1.14.3.
BentoBox version: 1.6.0-SNAPSHOT-b1225
Loaded Game Worlds:
acidisland_world (acidisland): Overworld, Nether, End
Loaded Addons:
AcidIsland 1.5.1-SNAPSHOT (ENABLED)
Biomes 1.5.2.1-SNAPSHOT-b124 (ENABLED)
Challenges 0.8.0-SNAPSHOT-#278 (ENABLED)
Level 1.5.1-SNAPSHOT (ENABLED)
Limits 0.2.3-SNAPSHOT (ENABLED)
WelcomeWarps 1.5.2-SNAPSHOT (ENABLED)

**Comment by tastybento** [comment]
Fixed with 5adf2a3ef93b3775392b98108f04e71e06817b44

Thanks!
