### ISSUE TITLE
that islandresetdeathreset: true is not working

### ISSUE THREAD

**Issue by Max05pl** [BentoBoxWorld/Level#63]
**Description**
The addon doesn't reset your deaths even tho it's enabled to islandresetdeathreset: true

**Steps to reproduce the behavior:**
1. Just try it.

**Expected behavior**
it should work

**Screenshots**
no need sir

**Server Information:**

[Please complete the following information:]
 - YAML
 - Multicraft (linux)
 - Java 8
 - bbox version: 1.5.3
 - Addons installed? yes level addon is 1.5.0
 - Other plugins? yes other plugins: multiverse, worldedit, worldguard, multiverse inv

**Additional context**
just doesn't work

**Comment by BONNe** [comment]
Will not work in YAML.

**Comment by tastybento** [comment]
It won't work at all because it's not actually implemented!

**Comment by tastybento** [comment]
This setting will be go and replaced by a setting in BSkyBlock's config.yml, etc. for 1.6.0.
See https://github.com/BentoBoxWorld/BentoBox/pull/817
