### ISSUE TITLE
Double slabs count as single slab

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Level#64]
**Description**
When 2 x `STONE_BRICK_SLAB` put on top of each other it becomes a STONE_BRICK_SLAB type double. It sounds logical to a player that this should count as 2 slabs, so double the points of 1 slab. Only the level add on sees this as 1 slab.

**Steps to reproduce the behavior:**
1. calculate island level
2. place 1 stone_brick_slab
3. calculate island level (the points of the slab is added)
4. place 1 stone_brick_slab on top of the previous slab. The block looks like 1 stone_brick, but it counts as 1 slab. 

**Expected behavior**
It would be nice if Level should see the difference between stone_brick_slab and stone_brick_slab double

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [JSON]
 - OS: [Linux]
 - Java Version: [Java 8]
 - BentoBox version: [1.6.0 build 1240]
 - Addons installed?
Running PAPER 1.13.2.
BentoBox version: 1.6.0-SNAPSHOT-b1240
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.5.2.1-SNAPSHOT-b125 (ENABLED)
BSkyBlock 1.5.3-SNAPSHOT (ENABLED)
Challenges 0.8.0-SNAPSHOT-#278 (ENABLED)
Level 1.5.1-SNAPSHOT (ENABLED)
Limits 0.2.3-SNAPSHOT (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
WelcomeWarps 1.5.2-SNAPSHOT (ENABLED)

**Comment by tastybento** [comment]
Thanks!
