### ISSUE TITLE
PlaceHolder bug(?)

### ISSUE THREAD

**Issue by Vogoun** [BentoBoxWorld/Level#65]
So i wanted Island level to show in chat before player names. 
Example - (%Level_bskyblock-island-level%) [Member] (playername) -> (message)

I searched for placeholders for Level addon and then used it. But it the is level is still same and it doesn´t change even after /is level, reload of plugin i am using for chat formating                         
 ( ChatManager )and reload of BentoBox.  

Showcase of config:

Owner:
      Format: "&8[&a %Level_bskyblock-island-level% &8] &7【&c&lOwner&7】 &c{player} &7» &7{message}"

**Comment by tastybento** [comment]
Please report:

- BentoBox version: [e.g. 1.6.0]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
