### ISSUE TITLE
TopTen

### ISSUE THREAD

**Issue by ronc617** [BentoBoxWorld/Level#67]
top Ten not being updated to file

[Server] Server thread/INFO Running SPIGOT 1.14.4.
[Server] Server thread/INFO BentoBox version: 1.6.0-SNAPSHOT-b1277
[Server] Server thread/INFO Database: JSON
[Server] Server thread/INFO Loaded Game Worlds:
[Server] Server thread/INFO acidisland_world (acidisland): Overworld, Nether, End
[Server] Server thread/INFO Loaded Addons:
[Server] Server thread/INFO AcidIsland 1.6.0-SNAPSHOT (ENABLED)
[Server] Server thread/INFO Biomes 1.5.2.1-SNAPSHOT-b126 (ENABLED)
 [Server] Server thread/INFO Challenges 0.8.0-SNAPSHOT-#282 (ENABLED)
 [Server] Server thread/INFO Level 1.6.0-SNAPSHOT (ENABLED)
23.07 09:40:34 [Server] Server thread/INFO Limits 0.2.3-SNAPSHOT (ENABLED)
23.07 09:40:34 [Server] Server thread/INFO WelcomeWarps 1.5.2-SNAPSHOT (ENABLED)

 [Server] Server thread/INFO 1. bigierc617 - 11961
 [Server] Server thread/INFO 2. Zhiqing - 4618
 [Server] Server thread/INFO 3. Wurztha - 1611

acidisland_world.json
{
  "uniqueId": "acidisland_world",
  "topTen": {
    "c7700b8a-4432-43fd-8d4a-3f7fb1efef6e": 11961,
    "09d1b101-2bad-407a-8d7b-351c6191688f": 4618
  }
}

**Comment by tastybento** [comment]
When are you checking the file? It's only saved when the server shuts down.

**Comment by ronc617** [comment]
The file is not saved and updated on server restarts
There will be a top 10 list while server is up and after a restart it will
go back to the old data

**Comment by ronc617** [comment]
Deleted all files related to level and let things rebuild
It now seems to be saving and updating the files at restart. You can close
out the ticket.
Thank you
