### ISSUE TITLE
Recalculate Island Levels

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Level#69]
**Is your feature request related to a problem? Please describe.**
A player which doesn't execute `/is level` to often does not benefit from a higher cobblestone gen tiera and will not end up in the Island Top Ten.

**Describe the solution you'd like**
A command to `/bsb level *` or `/bsb level all` to recalculate all existing islands.

**Describe alternatives you've considered**
I could gather all players and do `/bsb level playername` by hand. This would take hours and hours.
Or I might trigger the level calculation command when the player joins with an event, but the server then won't benefit from the time no player is online and the load is zero.

**Additional context**
In addition to issue 36, it would be handy if the recalculation of island could take place on a quite hour. For example: schedule a job at night for recalculation of all present islands perhaps daily or 
weekly. This way the Top Ten would and probably the purging proces to filter abandoned noob islands would be more accurate.

**Comment by tastybento** [comment]
The way I did this with ASkyBlock was to have a setting that would calculate the level when a player logged in. That spread the load and was naturally biased towards players who were active rather than those who had stopped playing and were just occupying the Top Ten. How about that?

**Comment by x1p** [comment]
Fine by me
