### ISSUE TITLE
Island level in chat is the same across the server regardless of per-player island level

### ISSUE THREAD

**Issue by johncsuti** [BentoBoxWorld/Level#70]
**Description**
Island level is the same for every user regardless of personal island level the placeholder in premissionsex will be replaced with op's island level

**Expected behavior**
island level is different based on persons island level so they can "show off"

**Server Information:**

 - Database being used (YAML, JSON, MySQL, MongoDB): [YAML]
 - OS: [UBUNTU 16.04 LTS]
 - Java Version: [Java 1.8.0 212]
 - BentoBox version: [BentoBox version: 1.5.0-SNAPSHOT-b1121]
 - Addons installed? [BSkyBlock 1.5.0 (ENABLED)
Challenges 0.7.5-SNAPSHOT-#248 (ENABLED)
Level 1.5.0-SNAPSHOT (ENABLED)
Limits 0.2.0-SNAPSHOT (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
WelcomeWarps 1.5.0-SNAPSHOT (ENABLED)]
 - Other plugins? [BentoBox, BetterChairs*, ChatInjector*, ClearLag, CratesPlus, Essentials, EssentialsChat, EssentialsSpawn, HolographicDisplays, Multiverse-Core, PermissionsEx*, PlaceholderAPI*, PluginHiderPlus*, PreventPortBypass*, ProtocolLib*, Scoreboard-revision*, SetTheSpawn, SilkSpawners, StackMob, SuperVanish, TimeVote, Trading*, Vault, ViaBackwards*, ViaRewind*, ViaVersion*, Votifier, VotingPlugin, WeatherVote, WorldEdit, WorldGuard]

**Additional context**
Server version: [Paper version git-Paper-641 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)]

**Comment by tastybento** [comment]
Are you able to try using the latest versions of BentoBox and BSkyBlock, etc.? i.e., 1.6.0

**Comment by johncsuti** [comment]
This is what i as op see
![2019-07-29_20 57 30](https://user-images.githubusercontent.com/22971404/62092584-ac03e480-b243-11e9-97d3-06568790c0d4.png)
and this is what my friend sees
![2019-07-29_20 57 21](https://user-images.githubusercontent.com/22971404/62092605-be7e1e00-b243-11e9-808e-7e4de4adccdd.png)
The levels are flipped and it should show the correct levels like it does on the scoreboard

**Comment by johncsuti** [comment]
and this is what i see when i type
![2019-07-29_21 00 26](https://user-images.githubusercontent.com/22971404/62092678-14eb5c80-b244-11e9-8744-b278f77bbca1.png)
and this is what my friend sees
![2019-07-29_21 00 29](https://user-images.githubusercontent.com/22971404/62092692-216fb500-b244-11e9-8dc8-010ff2ffaf9a.png)

**Comment by johncsuti** [comment]
it appears as though all island prefix's are being replaced by the end users island where the senders island should be replacing it, When its not very weird

**Comment by tastybento** [comment]
What is the config you are using for PEX to show these?

**Comment by johncsuti** [comment]
https://pastebin.com/YrDp7zLw

**Comment by johncsuti** [comment]
i took out all the sensitive data such as users information

**Comment by tastybento** [comment]
So, just to confirm the problem, for example:

1. tastybento, a member has an island level of 100. He sends a message to everyone on the server saying "hello"
2. johncsuti has an island level of 50. When he sees the message from tastybento it says <[50] [Member] tastybento> hello
3. LSPVicky is a member and she has an island of 25. When see sees the message from tastybento, it says <[25] [Member] tastybento> hello

Is that correct? I just want to super make sure. You showed me 2 way, but I just want to make sure a 3 way message looks like that.

**Comment by johncsuti** [comment]
That’s exactly what’s happening I’m not sure why that’s happening nothing makes sense I want the users to “fight” for top but they can’t if everyone’s username in chat appears to all be there own level

**Comment by Bricec6** [comment]
It's because of ChatInjector, I had the same problem and remove the plugin, then change the placeholder in my DeluxeChat, and everything works again

**Comment by johncsuti** [comment]
I need to know if this will work with essentialsxchat and essentialsx if it doesn't work with them i cant use it as i use essentialsx for kits that works wonderfully

**Comment by johncsuti** [comment]
Fixed after migrating network to luckperms instead of permissionsex and migrated essentialsxchat to chatmanager
