### ISSUE TITLE
Allow points for AIR

### ISSUE THREAD

**Issue by mattc4t** [BentoBoxWorld/Level#73]
**Is your feature request related to a problem? Please describe.**
Players' levels decrease as they mine stone in Caveblock.  The more players enlarge their cave, the lower their level goes...  This makes it impossible to do the challenges based on level.

**Describe the solution you'd like**
Provide a way to specify other than 0 points for counting AIR blocks.  That would allow me to set it to 1 for caveblock so as players mine stone, their score does not decrease.

  caveblock-world:
    AIR: 1

**Describe alternatives you've considered**
I've tried to decrease the value of stone to 0 - but that lowered everyone's level substantially.

**Additional context**

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/Level#world-specific-block-values

**Comment by tastybento** [comment]
Code changed to allow AIR to have value. You can give it a global value or like @BONNe wrote assign it just for the world.

**Comment by mattc4t** [comment]
Thank you!
