### ISSUE TITLE
bskyblock-version-build and level-version-build

### ISSUE THREAD

**Issue by SlimeDog** [BentoBoxWorld/Level#74]
#### Is your feature request related to a problem?

n/a

#### Describe the solution you'd like us to implement.

Please add build number to the dev builds of BSkyBlock and Level, as you do for BentoBox and Challenges. For example, today:
- bskyblock-1.6.0-SNAPSHOT-b390.jar

A consistent naming convention would be a bonus. (Challenges uses a different format from BentoBox.)

#### Describe alternatives you've considered.

At present, we have to add the build numbers to the file names ourselves (if we want to keep track at the filename level).

### Additional context

n/a

**Comment by tastybento** [comment]
Done!

**Comment by SlimeDog** [comment]
Thanks. 👍
