### ISSUE TITLE
Detailed breakdown of the level calculation

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/Level#75]
**Is your feature request related to a problem? Please describe.**
People don't understand why they gain levels and why they lose some... And sometimes us neither.

**Describe the solution you'd like**
I know ASB had that "level calculation breakdown" thing if you were executing the command in the console. What I suggest is not to have an as detailed thing as this one used to be (at least if we're showing something to the player), but to have a breakdown that gives you a sense of understanding what happens. Pretty much something like this:

```
Blocks: 10,457
Points:
 (* [point per block]: [number of blocks that gives that amount of point])
 * 1 point: 9,450 blocks
 * 10 points: 503 blocks
 * 50 points: 254 blocks
 * 100 points: 125 blocks
 * 200 points: 125 blocks
 * total: 64,680 points
Levels: 64,680 / 100 = 646 levels
Maluses:
 * Handicap: -25
 * Deaths: -5 inlcuding 2 deaths of yours (maximum: -10)
Final level: 616
```

Note that most of it should be translatable. I recommend the use of quite a lot of text variables as well.

**Describe alternatives you've considered**
Some other (~~premium~~) Skyblock plugins use a GUI for this. Basically, you calculate your level and there's a GUI that displays the amount of all the blocks you've got on your island and how many levels they're giving you.

This alternative, while maybe being complementary to the original idea, could also be designed as an addon or similar because interest for such a GUI can also be found in the Limits addon. That's why I'm dropping this here, yet I think it needs more thinking than the original idea.

**Additional context**
None.

**Comment by tastybento** [comment]
This is already supported. Just run the admin level command in the console and you get a full report.

**Comment by tastybento** [comment]
I like the idea of a GUI though. That could be nice for players.

**Comment by Poslovitch** [comment]
> This is already supported. Just run the admin level command in the console and you get a full report.

And that's still the point of my feature request. I want this breakdown to be prettified and shown systematically to users, when they execute the player level command. Our localization system being very flexible, we can have multi-lines texts with a lot of text variables in them.

> I like the idea of a GUI though. That could be nice for players.

I knew I've seen this GUI thing on an existing, and so did I found it (it was part of the old SkyblockEarth plugin):
![gif](https://i.postimg.cc/DfR4FHrM/76b53af569daaaaa654ef2d2d6e1dd1374b41ffb.gif)

The idea of having that per block view is quite nice, I admit.

**Comment by i9hdkill** [comment]
Would like to see that aswell. Currenlty hard limits of blocks are making players a hard time. Doesn't need to be a gui. But when running /is level, have some one-liner that says:
235 cobble blocks were not counted, as you reached the cobble limit of X

**Comment by tastybento** [comment]
This is basically done in the details GUI. Improvement requests can be made separately.
