### ISSUE TITLE
BSkyBlock levels placeholders

### ISSUE THREAD

**Issue by PrivatechStudios** [BentoBoxWorld/Level#78]
Hello!

I am using PlaceholdersAPI and i noticed BentoBox has a few BSkyBlock placeholders. You have many addons but they weren't listed there. My question is. Does the level addon have any placeholders? If it doesnt, it would be great if you added them.

Thanks in advance!

**Comment by BONNe** [comment]
So, you found bskyblock placeholders, and did not find level placeholders?
Interesting, as they are listed on the same page.

**Comment by PrivatechStudios** [comment]
> So, you found bskyblock placeholders, and did not find level placeholders?
> Interesting, as they are listed on the same page.

They are NOT listed there. Levels is a special addon for byskyblock. Perhaps you were looking at ASkyBlock placeholders? If you werent then check the "BentoBox" placeholders since the placeholders are not separated by addons int he BentoBox.

**Comment by BONNe** [comment]
Can you please provide a page where are you looking?

**Comment by PrivatechStudios** [comment]
> Can you please provide a page where are you looking?

https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bentobox

**Comment by PrivatechStudios** [comment]
Indeed the placeholder does exist tho i had to go trough many pages of github to find it: https://github.com/BentoBoxWorld/Level/wiki/Placeholders 
It is listed on the actual addon but not placeholderAPI.
Thanks for the replies. ~closed

**Comment by BONNe** [comment]
Sorry, https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bentobox wiki is not ours. We cannot be blamed for a thing that is created by different peoples and communities. 

Our wiki is in above each addon and bentobox plugin (code / issues .... / wiki / ...
where you can find information that we, not perfectly, but support...

https://github.com/BentoBoxWorld/BentoBox/wiki

and there are all placeholders and links to each addon page placeholders.

However, as you can see, not all pages are up to date, but still, we are trying, and at least the main page is updated.
