### ISSUE TITLE
Level -1

### ISSUE THREAD

**Issue by Vlieker** [BentoBoxWorld/Level#79]
My island is currently level -1...

I removed almost everything and built a flat island at the bedrock level, now my island is level -1

**Comment by tastybento** [comment]
Maybe you died once?

**Comment by tastybento** [comment]
Do **/bsb level (your name)** in console to see a report to explain why you are getting -1.

**Comment by BONNe** [comment]
Tasty, what about starting blueprint blocks?
Are they counted into a start level (so at the start should not be 0), or they are taken as world generated blocks and with them, initial level would be 0?

**Comment by tastybento** [comment]
@BONNe When an island is pasted there is an immediate level calculation done that is then used as a modifier for all future calculations. Typically, the reason players see a -1 level on start is because they have a death being counted.
