### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by Nedjii** [BentoBoxWorld/Level#82]

**Comment by tastybento** [comment]
I'm out for a few days so I can't look at this right now, but I will when I get back.

**Comment by Nedjii** [comment]
Ok, no problem !

**Comment by tastybento** [comment]
I just remembered, there's a SQLite bug in 1.6.0 BentoBox. Download the latest build from the CI server https://ci.codemc.org/job/BentoBoxWorld/job/BentoBox/ to get the fixed version. It'll be 1.7.0_SNAPSHOT, but it's essentially the same.

**Comment by Nedjii** [comment]
I'll better wait for the 1.7 to be released as i'm not hurry.

**Comment by Nedjii** [comment]
The placeholder doesn't update for some reason, I went from 52 lvl to 1000 and the placeholder keeps telling me 52 when /is level gives me the right number.

**Comment by Nedjii** [comment]
It started working again after restart and couldn't reproduce it, will tell here if it happens again.

**Comment by tastybento** [comment]
Sounds like a dupe of #94

**Comment by johncsuti** [comment]
I had a similar problem it wasn't updating mine was fixed with a server reboot. That should not be needed though.

**Comment by tastybento** [comment]
Level has been completely rewritten so this probably doesn't apply. Closing for now.
