### ISSUE TITLE
Ajouts du level %[gamemode]_visited_island_name%

### ISSUE THREAD

**Issue by AFGAME** [BentoBoxWorld/Level#84]
Cette variable pourrait faire en sorte que quand on soit sur un is voisin on voit son level dans le scoreboard ou autres ça serait super comme ajout.

**Comment by tastybento** [comment]
Request for a placeholder to show the level of the visited island so it can be shown in a scoreboard.

**Comment by Poslovitch** [comment]
Duplicate of #103, closing.
