### ISSUE TITLE
Auto recalculate level

### ISSUE THREAD

**Issue by Tina-King** [BentoBoxWorld/Level#89]
**Is your feature request related to a problem? Please describe.**
Currently, the island level does not automatically recalculate which means featherboard shows the wrong island level.

**Describe the solution you'd like**
When an island team member/leader joins the server it should recalculate and also a configurable option to automatically recalculate the level ever X minutes for each online island member/leader.

**Describe alternatives you've considered**
Im not aware of an alternative.

**Comment by tastybento** [comment]
In the latest version, there is a setting in config:

```
# Calculate island level on login
# This silently calculates the player's island level when they login
# This applies to all islands the player has on the server, e.g., BSkyBlock, AcidIsland
login: false
```

Change that setting to true and the level will be calculated on login. I won't do the auto calc every x minutes because that would bring pretty much every server to its knees from processing.

**Comment by Tina-King** [comment]
Thanks for the login feature.

Maybe it can recalculate only for members who placed a block on their island over X minutes ago, and will not recalculate again until X minutes after placing their next block?

Thanks,
Tina

**Comment by tastybento** [comment]
I understand the request, but it's a no-do from me. Level calc will be driven by players making the request.
