### ISSUE TITLE
Add ranks upon levelling up

### ISSUE THREAD

**Issue by SimplyIssac** [BentoBoxWorld/Level#91]
#### Is your feature request related to a problem?

A decent feature request which I believe could be nice is ranking up with your island level.

#### Describe the solution you'd like us to implement.

Say if a player reaches certain island level) you can add a group. 
For example: A player has reached level 250 for their island, it will automatically update their roles to tier2. Then if they reached level 500, they'd get tier3 and so on.

#### Describe alternatives you've considered.

Not sure at this point in time... 

### Additional context

N/A

Thanks for reading,
SimplyIssac.

**Comment by Poslovitch** [comment]
I suppose you mean being able to specify ranks upon reaching a certain island level? 
But that raises the issue of island reset or the island losing levels...

**Comment by SimplyIssac** [comment]
Well if they want to reset their island, then their level being reset obviously comes with that so their rank or whatever you want to call it also resets. I don't see how that could be an issue when it's their choice whether or not they reset their island. 

And please elaborate on the island losing levels? Because their level count would still be counted as per usual, but when reaching certain levels their rank will just be upgraded.  

Thank you for the response, much appreciated!

**Comment by tastybento** [comment]
This is something that is actually handled by the Challenges addon. i.e., a player can get a reward for reaching a specific island level. I think there are at least a few challenges that do this. Rewards can be e.g., money/perms/items, etc. You would give a perm or run a command on achieving the right island level.

>And please elaborate on the island losing levels? 

Island levels are determined by the blocks on the island and their associated values, so if a player were to lose their blocks, e.g. they get blown up by a creeper or dropped into the void, then the island level can go down.

As this is a feature that is provided by Challenges, I'll close it. If you think you need something more, let me know.
