### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by VozikCZE** [BentoBoxWorld/Level#94]
**Description**
Placeholder is displaying different island level than /is level.
Placeholder: %Level_bskyblock-island-level%
**Steps to reproduce the behavior:**
1. Use command /is level
2. Compare output from /is level and placeholder.

**Screenshots**
![image](https://user-images.githubusercontent.com/48393384/67788850-5376fa00-fa73-11e9-8bf2-2ae9a657f125.png)

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - OS: -
 - Java Version: 8
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed?
`[0;32mSpouštění [0;36mPAPER 1.14.4[0;32m.
> [K[17:39:42 INFO]: [0;32mVerze BentoBoxu: [0;36m1.8.0
> [K[17:39:42 INFO]: [0;32mDatabase: [0;36mJSON
> [K[17:39:42 INFO]: Načtené herní světy:
> [K[17:39:42 INFO]: [0;32mbskyblock_world ([0;36mBSkyBlock): Svět, Nether, End
> [K[17:39:42 INFO]: Načtené addony:
> [K[17:39:42 INFO]: [0;32mBSkyBlock [0;36m1.8.0 ([0;36mENABLED)
> [K[17:39:42 INFO]: [0;32mGreenhouses [0;36m0.4.2-SNAPSHOT ([0;36mENABLED)
> [K[17:39:42 INFO]: [0;32mLevel [0;36m1.8.0 ([0;36mENABLED)
> [K[17:39:42 INFO]: [0;32mLimits [0;36m1.7.0 ([0;36mENABLED)`
 - Other plugins?
`Plugins (37): BentoBox, BlockVersion*, ChatInjector*, CompostingPlus, CustomOreGen, DeluxeMenus, EpicSpawners, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, FastFarmStopper, HeadDatabase*, Jetpack, Jobs, LuckPerms, Multiverse-Core, MultiVIP*, PlaceholderAPI*, ProtocolLib, ProtocolSupport, Scoreboard-revision*, ShopGUIPlus, SkinsRestorer, SkQuery, Skript, skUtilities*, SkyblockWorldEdit*, TitleManager*, TradePlus, UltimateStacker, VanillaDispenserPlus*, Vault, VillagerOptimiser, Voting*, WorldEdit, YourAuction`

**Additional context**

**Comment by tastybento** [comment]
Please run `bsb level (name of player)` in the console and copy and paste the result here.

**Comment by johncsuti** [comment]
@tastybento happened to me as well seems to break without reasoning
![2019-12-05_19 26 17](https://user-images.githubusercontent.com/22971404/70285383-4dbcb480-1795-11ea-8e1d-b0fa6960a443.png)

**Comment by johncsuti** [comment]
Update it seems to stop working for me consistently after ./bbox reload is there a way to prevent this from happening? Other then placeholders not working on the reload command everything else works well.

**Comment by tastybento** [comment]
@johncsuti that is very good Information. I did a code walkthrough yesterday and I couldn’t see where it would be going wrong. Now I can focus on the reloading. 

I know right now that we do not handle placeholders in any special way when reloading. We may need to do something special like unregister the placeholder then register it again.

**Comment by johncsuti** [comment]
@tastybento I would say you should start with re-registering then at reload or at least unregister them then reload then register them again. You may also have luck just trying to register them as a final step in the reload.

**Comment by MorkaZ** [comment]
Hi, placeholder `Level_caveblock-island-level` completly does not work - it is always 0. Tested it in few plugins with CaveBlock. Please, fix it :(

**Comment by tastybento** [comment]
Level has been completely rewritten so this probably doesn't apply. Closing for now.
