### ISSUE TITLE
New Level System

### ISSUE THREAD

**Issue by ismail0234** [BentoBoxWorld/Level#97]
**Is your feature request related to a problem? Please describe.**
using the steam level system.

**Describe the solution you'd like**
New Island Level System. Examples:

- 100 point => 1 Level
- 200 point => 2 Level
- 300 point => 3 Level
- 400 point => 4 Level
- ....
- 900 point => 9 Level
- 1000 point =>10 Level
- 1200 point => 11 Level
- 1400 point => 12 Level
- 1600 point => 13 Level
- 1800 point => 14 Level
- ...
- 2800 point => 19 Level
- 3000 point => 20 Level
- 3300 point => 21 Level
- .....

Wouldn't this feature be really nice ?

**Comment by BONNe** [comment]
I would better prefer a math function that users could provide, which would create level curve.

f.e.
x = x + 100 => each 100 points is new level
x = x * 2 => each next level need 2x more points
x = x^2 => ...

**Comment by tastybento** [comment]
Yes - I'm actually working on this right now and just doing some checking:

```
# Island level calculation formula
# blocks - the sum total of all block values, less any death penalty
# level_cost - in a linear equation, the value of one level
# This formula can include +,=,*,/,sqrt,^,sin,cos,tan. Result will always be rounded to a long integer
level-calc: 3 * sqrt(blocks / level_cost)

```

**Comment by tastybento** [comment]
The `pointsToNextLevel` calculation is bit more complex.

**Comment by ismail0234** [comment]
https://steamcommunity.com/ How do you think the level system?

**Comment by tastybento** [comment]
@ismail0234 Thanks. Yes, I understand. By adding the ability to create your own system via a formula, you should be able to implement or approximate the Steam level. The basic idea is to require more blocks in order to gain levels so that the number of levels doesn't go crazy high.

**Comment by ismail0234** [comment]
@tastybento  I applied it. Works very well. The level jump was really worthwhile.

**Comment by tastybento** [comment]
I haven't updated the addon yet. :-) It's late here - I'll get something out tomorrow.

**Comment by ismail0234** [comment]
@tastybento I'm waiting :). My using steam level algorithm example:

https://stackoverflow.com/questions/34482614/mimik-leveling-algorithm

I've made changes to that.
