### ISSUE TITLE
Exclude from /is top

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Level#98]
**Is your feature request related to a problem? Please describe.**
I don't want Staff members present in the `is top`

**Describe the solution you'd like**
Exclusion list for certain players

**Describe alternatives you've considered**
The following permission is given by default:
```
  bskyblock.intopten:
    description: Player is in the top ten.
    default: true
```
So I tried to give this negative permission for staff. It seems to hide only staff members when they are online or been online that day. This does not function properly and thus seems not a stable solution. I would like to have a stable solution that always work.

**Additional context**
Using LuckPerms as permission plugin

**Comment by tastybento** [comment]
When are island levels calculated? If it is done when they are online, then their entry should never go into the top ten list at all. Could their island level be being calculated when they are offline somehow?

**Comment by x1p** [comment]
until now, staff members have been in the island top. I just recently gave the negative permission.
The `is top` is only calculated when a player performs the command.

**Comment by tastybento** [comment]
It'll work now. I also added an admin command so you can manually remove the staff from the top ten if they don't log in.

**Comment by x1p** [comment]
Im a little cautious to try. I've tried updating the level addon today and all islands dropped in level for some reason. I still have to figure out why and serup a test scenario to figure out what's going on.
Anyway, thank you very much for this.
